---
title: "Demography of Aging in South Saharan Africa"
output: 
  bookdown::pdf_document2:
    toc: false
    extra_dependencies: ["flafter"]
    number_sections: true
    df_print: kable
    highlight: tango
    keep_tex: true
    fig_caption: yes
fontsize: 11pt
geometry: margin=1in
header-includes:
  \usepackage{pdflscape}
  \usepackage{lscape}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.align = "center",
	fig.height = 4.5,
	fig.width = 5,
	message = FALSE,
	warning = FALSE,
  graphics.auto_pdf = FALSE
	)
```


```{r packages, include=FALSE}
# Load & Install Packages
pacman::p_load(
  ggtext,
  tidyr, 
  haven, 
  plyr, 
  dplyr, 
  magrittr,
  ggplot2, 
  CGPfunctions, 
  scales, 
  ggh4x, 
  cowplot, 
  stats,
  stringr,
  reshape2,
  directlabels,
  ggstream,
  patchwork,
  ggrepel,
  forcats,
  ggh4x

)
```

```{r data, include=FALSE}
# Define the base path for data files to avoid repeating paths
data_path <- "../data/preprocessed/"

# Helper function to load datasets
load_data <- function(file_name) {
  read_dta(file.path(data_path, file_name))
}

# Load datasets using helper function
ssa <- load_data("allcountries.dta")
projections <- load_data("population_projections_t1.dta")
dat <- load_data("summaryindicators.dta")
ssa_agg <- load_data("allcountries_means5year_weightspopsurvey.dta")
ssa_agg_non <- load_data("allcountries_means5year_noweights.dta")
pop_pro <- load_data("population_projections_allcountries.dta")

# Load and combine weighted and non-weighted datasets
subsaharan_weighted <- load_data("allcountries_means5year_weightspopsurvey_all.dta")
subsaharan_nonweighted <- load_data("allcountries_means5year_noweights_all.dta")

countries_weighted <- load_data("allcountries_means5year_weightspopsurvey_countries.dta")
countries_nonweighted <- load_data("allcountries_means5year_noweights_countries.dta")

# Add country identifiers and combine datasets
subsaharan_weighted$country <- 'ssa'
subsaharan_weighted <- rbind(subsaharan_weighted, countries_weighted)

subsaharan_nonweighted$country <- 'ssa'
subsaharan_nonweighted <- rbind(subsaharan_nonweighted, countries_nonweighted)


```



```{r}
order <- c("Sub-Saharan Africa", "India", "China", "Rest of World")
keepobs = c('World', 'India', 'China', 'Sub-Saharan Africa')
totpop = pop_pro %>% 
  select(
    countryregion, 
    pop_total_1990,
    pop_total_2020,
    pop_total_2050,
    pop_total_2100
  ) %>% 
  filter(
    countryregion %in% keepobs
    ) 
totpop = rbind(
  totpop, 
  c("Rest of World", as.vector(t(totpop[4, 2:5])) - as.vector(t(totpop[3, 2:5]))-as.vector(t(totpop[2, 2:5]))-as.vector(t(totpop[1, 2:5])))
  ) 
totpop = gather(totpop , condition, measurement, pop_total_1990:pop_total_2100, factor_key=TRUE)
totpop$condition = str_remove_all(totpop$condition, "pop_total_")
totpop = totpop %>% filter(countryregion!='World')
totpop$measurement = as.numeric(totpop$measurement)
totpop$condition = as.numeric(totpop$condition)
totpop = totpop %>% 
  mutate(countryregion = factor(countryregion, levels=order)) 

over60 = pop_pro %>% 
  select(
    countryregion, 
    pop_60plus_1990,
    pop_60plus_2020,
    pop_60plus_2050,
    pop_60plus_2100
  ) %>% 
  filter(countryregion %in% keepobs) 

over60 = rbind(
  over60, 
  c("Rest of World", as.vector(t(over60[4, 2:5])) - as.vector(t(over60[3, 2:5])) - as.vector(t(over60[2, 2:5])) - as.vector(t(over60[1, 2:5])))
  ) 

over60 = gather(
  over60 , condition, measurement, pop_60plus_1990:pop_60plus_2100, factor_key=TRUE
  )
over60$condition = str_remove_all(over60$condition, "pop_60plus_")
over60 = over60 %>% filter(countryregion!='World')
over60$measurement= as.numeric(over60$measurement)
over60$condition= as.numeric(over60$condition)

over60 = over60 %>% 
  mutate(countryregion = factor(countryregion, levels=order)) 

```



```{r}
countries <- c("China", "India", "Sub-Saharan Africa")
colors_scheme = c("#800000", "#2f4b7c",  "#8eb67d")
breaks_numer = c(1990,2020,2050, 2100)
breaks_text = c("1990","2020","2050", "2100")

dep_rat_ov60 = pop_pro %>%  
  filter(countryregion %in% countries) %>%  
  select(
    countryregion, 
    depratio_15to59_1990,
    depratio_15to59_2020, 
    depratio_15to59_2050, 
    depratio_15to59_2100
    )
dep_rat_ov60 <- data.frame(
  lapply(dep_rat_ov60, function(x) if(is.numeric(x)) round(x, 2) else x)
  )
dep_rat_ov60 = gather(dep_rat_ov60 , year, ratio, depratio_15to59_1990:depratio_15to59_2100, factor_key=TRUE)
dep_rat_ov60$year = as.numeric(str_remove_all(dep_rat_ov60$year, "depratio_15to59_"))
dep_rat_ov60 = dep_rat_ov60 %>% 
  group_by(countryregion) %>% 
  mutate(
    name_lab = if_else(((year == 2100)), countryregion, NA_character_),
    name_lab = if_else(
      ((name_lab == 'Sub-Saharan Africa')), 'Sub-Saharan Africa\n         Average', name_lab)) %>% 
  ungroup() 

old_age_rat_ov60 = pop_pro %>% 
  filter(countryregion %in% countries) %>%  
  select(
    countryregion, 
    oldagedepratio_15to59_1990, 
    oldagedepratio_15to59_2020,
    oldagedepratio_15to59_2050,
    oldagedepratio_15to59_2100
    )

old_age_rat_ov60 = gather(
  old_age_rat_ov60, 
  year, 
  ratio, 
  oldagedepratio_15to59_1990:oldagedepratio_15to59_2100, factor_key=TRUE
  )

old_age_rat_ov60$year = as.numeric(str_remove_all(old_age_rat_ov60$year, "oldagedepratio_15to59_"))
old_age_rat_ov60= old_age_rat_ov60 %>% 
  group_by(countryregion) %>% 
  mutate(
    name_lab = if_else(((year == 2100)), countryregion, NA_character_)
  ) %>% 
  ungroup() 
old_age_rat_ov60 <- data.frame(lapply(old_age_rat_ov60, function(x) if(is.numeric(x)) round(x, 2) else x))

old_age_rat_ov60 = old_age_rat_ov60 %>% 
    mutate(
    name_lab = if_else(((name_lab == 'Sub-Saharan Africa')), 'Sub-Saharan Africa\n             Avg.', name_lab)
)

depratov60 <- ggplot(
  dep_rat_ov60, aes(year, ratio, group=countryregion)
  ) +
  geom_line(
    aes(color = countryregion, size=countryregion)
    ) + 
    scale_size_manual(values = c(0.9,0.9, 1.6)) +
    theme_minimal() +
    geom_text_repel(
    aes(color = countryregion, label = name_lab),
    segment.angle = 10,
    size = 7.5,
    direction = "y",
    hjust = 0,
    vjust = 1.7,
    segment.size = .4,
    segment.alpha = .5,
    segment.linetype = "dotted",
    box.padding = .2,
    segment.curvature = -0.1
    ) +
  geom_text_repel(
    aes(color = countryregion, label = ratio),
    segment.angle = 20,
    size = 6,
    direction = "y",
    hjust = 0,
    vjust = -1.8,
    segment.size = 1.1,
    segment.alpha = .5,
    segment.linetype = "dotted",
    box.padding = .4,
    segment.curvature = -0.1
    ) +
   scale_color_manual(
    values = colors_scheme  ) +  
    coord_cartesian(
    clip = "off",
  ) +    
  theme_minimal() +
  labs(x="", y="", title='**E.-** General Population (Dependency Ratio)')+
   theme(
     panel.grid.minor  = element_blank(),
     panel.grid.major  = element_line(linetype = 'dotted'),
     axis.text.y=element_blank(),
     axis.title = element_markdown(margin = margin(l = 20, b=20), size=24, face='bold', vjust = +3, color="#344771"),
     text = element_text( size=20, color="#344771"),
     plot.title = element_markdown(size=20, color="#344771", hjust = 0.5),
     axis.text = element_markdown( size=20,margin = margin(5,0,0,0)),
     plot.background = element_blank(),
     panel.background = element_blank(),
     plot.margin = margin(1,20,0, 0),
     legend.position = "none",
     axis.line.x = element_line(size = 0.5, colour = "#344771", linetype=1)
     ) +
  scale_x_continuous(breaks=breaks_numer,labels = breaks_text) +
  scale_y_continuous(limits = c(0, 1.5), breaks = seq(0, 1.50, 0.25), labels = c("0", "", "0.5", "", "1", "", "1.50"), expand = c(0, 0))

oldageratov60 = ggplot(old_age_rat_ov60, aes(year, ratio, group=countryregion)) +
  theme(legend.position = "none") +
  geom_line(
    aes(color = countryregion, size=countryregion)
    ) + 
    scale_size_manual(values = c(0.9,0.9, 1.6)) +
  scale_color_manual(
    values = colors_scheme
    ) +  
  coord_cartesian(
    clip = "off"
    ) +
  geom_text_repel(
    aes(color = countryregion, label = ratio),
    segment.size = 1.1,
    
    segment.angle = 20,
    size = 6,
    direction = "y",
    hjust = 0,
    vjust = -1.98,
    segment.alpha = .5,
    segment.linetype = "dotted",
    box.padding = .4,
    segment.curvature = -0.1
    ) +
  labs(x="", y="", title='**F.-** Over 60 Population (Dependency Ratio)')+
    theme_minimal() +

  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(linetype = 'dotted'),
    axis.text.y = element_blank(),
    text = element_text( size=20, color="#344771"),
    plot.title = element_markdown(size=20,     color="#344771", hjust = 0.5),
    axis.text.x = element_markdown( size=20,margin = margin(5,0,0,0)),
    strip.background=element_blank(),
    panel.background = element_blank(),
    plot.background = element_blank(),
    plot.margin = margin(0,20,0,2),
    axis.line.x = element_line(size = 0.5, colour = "#344771", linetype=1),
    legend.position = "none",
  ) +   
  scale_x_continuous(breaks=breaks_numer,labels = breaks_text)+
    scale_y_continuous(limits = c(0, 1.5), breaks = seq(0, 1.50, 0.25), labels = c("0", "-", "0.5", "-", "1", "1.25", "1.50")) 
```





```{r}
dep_rat_ov65 = pop_pro %>%  
  filter(countryregion %in% countries) %>%  
  select(
    countryregion, 
    depratio_15to64_1990,
    depratio_15to64_2020, 
    depratio_15to64_2050, 
    depratio_15to64_2100
    )
dep_rat_ov65 <- data.frame(
  lapply(dep_rat_ov65, function(x) if(is.numeric(x)) round(x, 2) else x)
  )
dep_rat_ov65 = gather(dep_rat_ov65 , year, ratio, depratio_15to64_1990:depratio_15to64_2100, factor_key=TRUE)
dep_rat_ov65$year = as.numeric(str_remove_all(dep_rat_ov65$year, "depratio_15to64_"))
dep_rat_ov65 = dep_rat_ov65 %>% 
  group_by(countryregion) %>% 
  mutate(
    name_lab = if_else(((year == 2100)), countryregion, NA_character_),
    name_lab = if_else(
      ((name_lab == 'Sub-Saharan Africa')), 'Sub-Saharan Africa\n         Average', name_lab)) %>% 
  ungroup() 

old_age_rat_ov65 = pop_pro %>% 
  filter(countryregion %in% countries) %>%  
  select(
    countryregion, 
    oldagedepratio_15to64_1990, 
    oldagedepratio_15to64_2020,
    oldagedepratio_15to64_2050,
    oldagedepratio_15to64_2100
    )

old_age_rat_ov65 = gather(
  old_age_rat_ov65, 
  year, 
  ratio, 
  oldagedepratio_15to64_1990:oldagedepratio_15to64_2100, factor_key=TRUE
  )

old_age_rat_ov65$year = as.numeric(str_remove_all(old_age_rat_ov65$year, "oldagedepratio_15to64_"))
old_age_rat_ov65 = old_age_rat_ov65 %>% 
  group_by(countryregion) %>% 
  mutate(
    name_lab = if_else(((year == 2100)), countryregion, NA_character_)
  ) %>% 
  ungroup() 
old_age_rat_ov65 <- data.frame(lapply(old_age_rat_ov65, function(x) if(is.numeric(x)) round(x, 2) else x))

old_age_rat_ov65 = old_age_rat_ov65 %>% 
    mutate(
    name_lab = if_else(((name_lab == 'Sub-Saharan Africa')), 'Sub-Saharan Africa\n             Avg.', name_lab)
)

depratov65 <- ggplot(
  dep_rat_ov65, aes(year, ratio, group=countryregion)
  ) +
  geom_line(
    aes(color = countryregion, size=countryregion)
    ) + 
    scale_size_manual(values = c(0.9,0.9, 1.6)) +
    theme_minimal() +
    geom_text_repel(
    aes(color = countryregion, label = name_lab),
    segment.angle = 10,
    size = 7.5,
    direction = "y",
    hjust = 0,
    vjust = 1.7,
    segment.size = .4,
    segment.alpha = .5,
    segment.linetype = "dotted",
    box.padding = .2,
    segment.curvature = -0.1
    ) +
  geom_text_repel(
    aes(color = countryregion, label = ratio),
    segment.angle = 20,
    size = 6,
    direction = "y",
    hjust = 0,
    vjust = -1.8,
    segment.size = 1.1,
    segment.alpha = .5,
    segment.linetype = "dotted",
    box.padding = .4,
    segment.curvature = -0.1
    ) +
   scale_color_manual(
    values = colors_scheme  ) +  
    coord_cartesian(
    clip = "off",
  ) +    
  theme_minimal() +
  labs(x="", y="", title='**A.-** General Population (Dependency Ratio)')+
   theme(
     panel.grid.minor  = element_blank(),
     panel.grid.major  = element_line(linetype = 'dotted'),
     axis.text.y=element_blank(),
     axis.title = element_markdown(margin = margin(l = 20, b=20), size=24, face='bold', vjust = +3, color="#344771"),
     text = element_text( size=20, color="#344771"),
     plot.title = element_markdown(size=20, color="#344771", hjust = 0.5),
     axis.text = element_markdown( size=20,margin = margin(5,0,0,0)),
     plot.background = element_blank(),
     panel.background = element_blank(),
     plot.margin = margin(1,20,0, 0),
     legend.position = "none",
     axis.line.x = element_line(size = 0.5, colour = "#344771", linetype=1)
     ) +
  scale_x_continuous(breaks=breaks_numer,labels = breaks_text) +
  scale_y_continuous(limits = c(0, 1.5), breaks = seq(0, 1.50, 0.25), labels = c("0", "", "0.5", "", "1", "", "1.50"), expand = c(0, 0))

oldageratov65 = ggplot(old_age_rat_ov65, aes(year, ratio, group=countryregion)) +
  theme(legend.position = "none") +
  geom_line(
    aes(color = countryregion, size=countryregion)
    ) + 
    scale_size_manual(values = c(0.9,0.9, 1.6)) +
  scale_color_manual(
    values = colors_scheme
    ) +  
  coord_cartesian(
    clip = "off"
    ) +
  geom_text_repel(
    aes(color = countryregion, label = ratio),
    segment.size = 1.1,
    
    segment.angle = 20,
    size = 6,
    direction = "y",
    hjust = 0,
    vjust = -1.98,
    segment.alpha = .5,
    segment.linetype = "dotted",
    box.padding = .4,
    segment.curvature = -0.1
    ) +
  labs(x="", y="", title='**B.-** Over 65 Population (Dependency Ratio)')+
    theme_minimal() +

  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(linetype = 'dotted'),
    axis.text.y = element_blank(),
    text = element_text( size=20, color="#344771"),
    plot.title = element_markdown(size=20,     color="#344771", hjust = 0.5),
    axis.text.x = element_markdown( size=20,margin = margin(5,0,0,0)),
    strip.background=element_blank(),
    panel.background = element_blank(),
    plot.background = element_blank(),
    plot.margin = margin(0,20,0,2),
    axis.line.x = element_line(size = 0.5, colour = "#344771", linetype=1),
    legend.position = "none",
  ) +   
  scale_x_continuous(breaks=breaks_numer,labels = breaks_text)+
    scale_y_continuous(limits = c(0, 1.5), breaks = seq(0, 1.50, 0.25), labels = c("0", "-", "0.5", "-", "1", "1.25", "1.50")) 
```




```{r}
projec_am2 = pop_pro%>%  select(countryregion, oldagedepratio_15to64_1990, oldagedepratio_15to64_2020, oldagedepratio_15to64_2050)

prod = gather(pop_pro , year, ratio, oldagedepratio_15to64_1990:oldagedepratio_15to64_2050, factor_key=TRUE)
prod$year = as.numeric(str_remove_all(prod$year, "oldagedepratio_15to64_"))

prod$ratio = prod$ratio
```



```{r pop60compssss, echo=FALSE, fig.height=7.5, fig.width=15, dev = c("png"), dpi=300}

cent <- function(
    dat,
    sel
){
  dat = dat[
  with(dat, order(countryregion)),
  ]
  tot = dat %>%
      filter(condition==2100) %>% tail(sel) %>% select(measurement) %>% sum()
  rest = dat %>%
      filter(condition==2100) %>% tail(sel) %>% head(1) %>% select(measurement) %>% sum()/2
  num = tot-rest
return(num)
}

end_val <- function(
    dat,
    year
){
 size = dat %>% 
   filter(condition==year) %>% 
   select(measurement) %>% sum()
return(size)
}

sz_tot=6
size_share=6

stacked_labels <- data.frame(
  labels = rev(order),
  countryregion = rev(order),
  condition = c(2060, 2069, 2070, 2055),
  measurement = c(2670000, 5300000, 6600000, 8600000),
  color = c("black", "white", "white","black")
)
pal = c(
     # sub-saharan africa
    "#8eb67d",
     # india
    "#2f4b7c",
     # china
    "#800000",
     # rest of the world
    "#C7C9CB"

  )

fig1a = ggplot(
  totpop, 
  aes(condition, measurement, fill=countryregion, label=countryregion, fill=countryregion)) +
  geom_area(type = "ridge" , bw=1)  +
    geom_text(
      data=stacked_labels,
      aes(condition, measurement, label=labels),
      hjust=0,
      vjust=0.5,
    color=stacked_labels$color,
    size=8
  ) +
  annotate(
    "text", 
    x = 2100.2, 
    y = cent(totpop, 1),
    label = "· 4.6B",
    hjust=0,
    color="#818589",
    #fontface="bold",
    size=size_share
    ) +
  annotate(
    "text", 
    x = 2100.2, 
    y = cent(totpop, 2),
    label = "· 0.8B",
    hjust=0,
    lineheight=.8,
    color=pal[3],
    #fontface="bold",
    size=size_share
    ) +
  annotate(
    "text", 
    x = 2100.2, 
    y = cent(totpop, 3),
    label = "· 1.5B",
    hjust=0,
    lineheight=.8,
    color=pal[2],
    #fontface="bold",
    size=size_share
    ) +
  annotate(
    "text", 
    x = 2100.2, 
    y = cent(totpop, 4),
    label = "· 3.4B",
    hjust=0,
    lineheight=.8,
    color=pal[1],
    #fontface="bold",
    size=size_share
    ) +
  geom_segment(
    aes(
      x = 2050, 
      xend = 2050, 
      y = 0, 
      yend = end_val(totpop, 2050)
      ),
    color="black", 
    size=0.3
    ) +  
  geom_point(
    aes(x = 2050, y = end_val(totpop, 2050)),
    color="black"
    ) +
  annotate(
    "text", 
    x = 2050, 
    y = end_val(totpop, 2050) + 400000,
    label = "9.7B",
    hjust=0.5,
    size=sz_tot,
    lineheight=.8
    ) +
  geom_segment(
    aes(
      x = 2020, 
      xend = 2020, 
      y = 0, 
      yend = end_val(totpop, 2020)
      ),
    color="black", 
    size=0.3
    ) +  
  geom_point(
    aes(x = 2020, y = end_val(totpop, 2020)),
    color="black"
    ) +
  annotate(
    "text", 
    x = 2020, 
    y = end_val(totpop, 2020) + 400000,
    label = "7.8B",
    hjust=0.5,
    size=sz_tot,
    lineheight=.8
    ) +
  geom_segment(
    aes(
      x = 1990, 
      xend = 1990, 
      y = 0, 
      yend = end_val(totpop, 1990)
      ),
    color="black", 
    size=0.3
    ) +  
  geom_point(
    aes(x = 1990, y = end_val(totpop, 1990)),
    color="black"
    ) +
  annotate(
    "text", 
    x = 1990, 
    y = end_val(totpop, 1990) + 400000,
    label = "5.3B",
    hjust=0.5,
    size=sz_tot,
    lineheight=.8
    )+
  geom_segment(
    aes(
      x = 2100, 
      xend = 2100, 
      y = 0, 
      yend = end_val(totpop, 2100)
      ),
    color="black", 
    size=0.3
    ) +
  geom_point(
    aes(x = 2100, y = end_val(totpop, 2100)),
    color="black"
    ) +
  annotate(
    "text", 
    x = 2100, 
    y = end_val(totpop, 2100) + 400000,
    label = "10.3B",
    hjust=0.5,
    size=sz_tot,
    lineheight=.8
    ) +
  
  scale_fill_manual(values=pal) +
  coord_cartesian(clip = "off") +
  theme_minimal() +
  labs(title='**A.** General Population (Total)', y="", x="") +
  theme(
    panel.grid = element_blank(),
    axis.text.y=element_blank(),
    plot.title = element_markdown(size=20,     color="#344771", hjust = 0.5),
    axis.text.x = element_text(size=20,margin = margin(5,0,0,0)),
    plot.margin = margin(-1,20,0,2),
    legend.position = "none",
  ) +
  scale_x_continuous(
    breaks=c(1990,2020,2050, 2100), 
    labels=c("1990","2020","2050", "2100")
    )

```

```{r}

m = aggregate(over60$measurement, by=list(over60$condition), FUN=sum)
n = aggregate(totpop$measurement, by=list(totpop$condition), FUN=sum)

fun <- function(x, character = FALSE) {
  
  l = sprintf("%.0f",  x	/1000)

  vec = l[-1] 
  #vec = lapply(vec, FUN=format(x, commas=true))

  return(vec)
  
}


```


```{r}
iii= totpop %>% filter(condition==2100)
iii = aggregate(iii$measurement, by=list(iii$condition, iii$countryregion), FUN=sum)
iii
iii=iii %>% select(1,3)
apply(iii, 1, fun)
```

```{r}
ii= over60 %>% filter(condition==2100)
ii = aggregate(ii$measurement, by=list(ii$condition, ii$countryregion), FUN=sum)
ii
ii=ii %>% select(1,3)
apply(ii, 1, fun)
```

```{r}
apply(n, 1, fun)
apply(m, 1, fun)

```


```{r}
over60 = over60 %>% 
  mutate(countryregion = factor(countryregion, levels=order)) 

fig1b = ggplot(
  over60, 
  aes(condition, measurement, fill=countryregion, label=countryregion, fill=countryregion)
  ) +
  geom_area(type = "ridge" , bw=1) +
  annotate(
    "text", 
    x = 2100.2, 
    y = cent(over60, 1),
    label = "· 1.5B",
    hjust=0,
    color="#818589",
    #fontface="bold",
    size=size_share
    ) +
   annotate(
    "text", 
    x = 2100.2, 
    y = cent(over60, 2),
    label = "· 362M",
    hjust=0,
    color=pal[3],
    #fontface="bold",
    size=size_share
    ) +
   annotate(
    "text", 
    x = 2100.2, 
    y = cent(over60, 3),
    label = "· 552M",
    hjust=0,
    color=pal[2],
    #fontface="bold",
    size=size_share
    ) +
   annotate(
    "text", 
    x = 2100.2, 
    y = cent(over60, 4),
    label = "· 644M",
    hjust=0,
    color=pal[1],
    #fontface="bold",
    size=size_share
    ) +
  geom_segment(
    aes(
      x = 1990, 
      xend = 1990, 
      y = 0, 
      yend = end_val(over60, 1990)
      ),
    color="black", 
    size=0.3
    ) +  
  geom_point(
    aes(x = 1990, y = end_val(over60, 1990)),
    color="black"
    ) +
  annotate(
    "text", 
    x = 1990, 
    y = end_val(over60, 1990) + 120000,
    label = "483M",
    hjust=0.5,
    size=sz_tot,
    lineheight=.8
    ) +
  geom_segment(
    aes(
      x = 2020, 
      xend = 2020, 
      y = 0, 
      yend = end_val(over60, 2020)
      ),
    color="black", 
    size=0.3
    ) +  
  geom_point(
    aes(x = 2020, y = end_val(over60, 2020)),
    color="black"
    ) +
  annotate(
    "text", 
    x = 2020, 
    y = end_val(over60, 2020) + 120000,
    label = "1,061M",
    hjust=0.5,
    size=sz_tot,
    lineheight=.8
    ) +
  geom_segment(
    aes(
      x = 2050, 
      xend = 2050, 
      y = 0, 
      yend = end_val(over60, 2050)
      ),
    color="black", 
    size=0.3
    ) +  
  geom_point(
    aes(x = 2050, y = end_val(over60, 2050)),
    color="black"
    ) +
  annotate(
    "text", 
    x = 2050, 
    y = end_val(over60, 2050) + 120000,
    label = "2,132M",
    hjust=0.5,
    size=sz_tot,
    lineheight=.8
    ) + 
  geom_segment(
    aes(
      x = 2100, 
      xend = 2100, 
      y = 0, 
      yend = end_val(over60, 2100)
      ),
    color="black", 
    size=0.3
    ) +  
  geom_point(
    aes(x = 2100, y = end_val(over60, 2100)),
    color="black"
    ) +
  annotate(
    "text", 
    x = 2100, 
    y = end_val(over60, 2100) + 120000,
    label = "3,084M",
    hjust=0.5,
    size=sz_tot,
    lineheight=.8
    ) +
  scale_fill_manual(values=pal) +
  coord_cartesian(clip = "off") +
  theme_minimal() +
  labs(title='**B.** Over 60 Population (Total)', y="", x="") +
  theme(
    panel.grid = element_blank(),
    axis.text.y=element_blank(),
    plot.title = element_markdown(size=20,     color="#344771", hjust = 0.5),
    axis.text.x = element_text(size=20,margin = margin(5,0,0,0)),
    plot.margin = unit(c(0, 0.75, 0, 0),"inches"),
    legend.position = "none",
  ) +
  scale_x_continuous(
    breaks=c(1990, 2020, 2050, 2100), 
    labels=c("1990","2020","2050", "2100")
    )

```




```{r}
library(ggbrace)
totpop$name_lab = c(
   NA, NA, NA, NA, '+ 24 %', '+ 60 %','+ 123 %', NA, 
                    
                   '- 8 %', '+ 20 %','+ 90 %', NA,

                    
                   '- 42 %', '- 8 %','+ 63 %', NA

                  
                                      )

totpop$measurement_x= c(
  NA, NA, NA, NA,
  1421243, 1600170, 2776948, NA,
  1421243, 1600170, 2776948, NA,
  1421243, 1600170, 2776948, NA)

```


```{r}
first=870452.3
last=1396387.1	
(last	-first	)/first	*100
```


```{r}
first=1396387.1
last=2111548.8		
((last	-first	)/2) +first
```


```{r}
totpop$lab =c(
   '1.1 B', '0.9 B', '0,5 B', NA,NA, NA, NA, NA, 
                    
                   NA, NA, NA, NA,

                    
                   '0.8 B', '1.5 B','3.4 B', NA

                  
                                      )
```

```{r}
fig1c = ggplot(
  totpop %>% filter(countryregion != 'Rest of World'), 
  aes(condition, measurement, fill = countryregion, label = countryregion)
  ) +
  geom_line(aes(color = countryregion, size = countryregion)) + 
  scale_size_manual(values = c(1.9, 0.9, 0.9)) +
  geom_label(
    data = . %>% mutate(
      condition = case_when(
        condition %in% c(1990) ~ NA,
        condition == 2020 ~ 2005,
        condition == 2050 ~ 2035,
        condition == 2100 ~ 2075
      ),
      measurement = case_when(
        name_lab == '+ 63 %' ~ 2776948, 
        name_lab == '- 8 %' ~ 1600170,
        name_lab == '- 42 %' ~ 1039655,
        name_lab == '+ 123 %' ~ 803083.2,
        name_lab == '+ 60 %' ~ 1133420 - 40000,
        name_lab == '+ 24 %' ~ 1289317,
        name_lab == '+ 20 %' ~ 1533439 + 40000,
        name_lab == '- 8 %' ~ 1068783,
        name_lab == '+ 90 %' ~ 1753968
      )
    ),
    aes(label = name_lab, colour = countryregion), 
    fill = 'white', 
    size = 5,
    check_overlap = FALSE
  ) +
  geom_text_repel(
    aes(color = countryregion, label = lab),
    segment.angle = 1,
    size = 4,
    vjust = -1,
    segment.size = .5,
    segment.alpha = .5,
    segment.linetype = "dotted",
    segment.curvature = -0.1
  ) +
  coord_cartesian(clip = "off") +
  theme_minimal() +
  labs(title = '**C.** General Population (Growth)', y = "", x = "") +
  geom_point(aes(color = countryregion)) +
  theme(
    panel.grid = element_blank(),
    axis.text.y = element_blank(),
    plot.title = element_markdown(size = 20, color = "#344771", hjust = 0.5),
    axis.text.x = element_text(size = 20, margin = margin(5, 0, 0, 0)),
    plot.margin = unit(c(0, 0.75, 0, 0), "inches"),
    legend.position = "none",
    text = element_text(size = 20),
    panel.grid.major.x = element_line(color = "grey", size = 0.3, linetype = 2)
  ) +
  scale_x_continuous(
    breaks = c(1990, 2020, 2050, 2100), 
    labels = c("1990", "2020", "2050", "2100")
  ) +
  scale_color_manual(values = pal) +
  scale_y_continuous(
    breaks = c(0, 500000, 1000000, 1500000, 2000000, 2500000, 3000000, 3500000), 
    labels = c("0", "-", "1B", "-", "2B", "-", "3B", "-"),
    limits = c(0, 3500000)
  ) +
  # Adding individual curves for each section
  geom_curve(
    aes(x = 1990, xend = 2019, y = -5000, yend = 40000),
    inherit.aes = FALSE, color = "grey", curvature = -0.3
  ) +
  geom_curve(
    aes(x = 2021, xend = 2049, y = -5000, yend = 40000),
    inherit.aes = FALSE, color = "grey", curvature = -0.3
  ) +
  geom_curve(
    aes(x = 2051, xend = 2100, y = -5000, yend = 40000),
    inherit.aes = FALSE, color = "grey", curvature = -0.3
  )

```



```{r}

over60$name_lab = c(
   NA, NA, NA, NA, '+ 171 %', '+ 155 %','+ 121 %', NA, 
                    
                   '+ 100 %', '+ 144 %','+ 194 %', NA,

                    
                   '- 29 %', '+ 59 %','+ 313 %', NA

                  
                                      )

over60$lab =c(
   '94 M ', '57 M ', '24 M', NA,NA, NA, NA, NA, 
                    
                   NA, NA, NA, NA,

                    
                   '362 M', '552 M','644 M', NA

                  
                                      )

```



```{r}
first=93668.50
last=254160.73	
((last	-first	)/2) +first
```



```{r}

fig1d = ggplot(
  over60 %>% filter(countryregion != 'Rest of World'), 
  aes(condition, measurement, fill = countryregion, label = countryregion)
) +
  geom_line(aes(color = countryregion, size = countryregion)) + 
  geom_point(aes(color = countryregion)) +
  scale_size_manual(values = c(1.9, 0.9, 0.9)) +
  geom_label(data = . %>% mutate(
    condition = case_when(
      condition %in% c(1990) ~ NA,
      condition == 2020 ~ 2005,
      condition == 2050 ~ 2035,
      condition == 2100 ~ 2075
    ),
    measurement = case_when(
      name_lab == '+ 313 %' ~ 400078.6, 
      name_lab == '+ 59 %' ~ 449769.9 + 20000,
      name_lab == '- 29 %' ~ 435510.7,
      name_lab == '+ 194 %' ~ 104476.2,
      name_lab == '+ 144 %' ~ 244946.5,
      name_lab == '+ 100 %' ~ 381784.9,
      name_lab == '+ 121 %' ~ 38513.54,
      name_lab == '+ 155 %' ~ 99004.16,
      name_lab == '+ 171 %' ~ 173914.6
    )
  ), aes(label = name_lab, colour = countryregion), fill = 'white', size = 5, check_overlap = TRUE) +
  geom_text_repel(
    aes(color = countryregion, label = lab),
    segment.angle = 1,
    size = 4,
    vjust = -1,
    segment.size = 0.5,
    segment.alpha = 0.5,
    segment.linetype = "dotted",
    segment.curvature = -0.1
  ) +
  coord_cartesian(clip = "off") +
  theme_minimal() +
  labs(title = '**D.** Over 60 Population (Growth)', y = "", x = "") +
  theme(
    panel.grid = element_blank(),
    axis.text.y = element_blank(),
    plot.title = element_markdown(size = 20, color = "#344771", hjust = 0.5),
    axis.text.x = element_text(size = 20, margin = margin(5, 0, 0, 0)),
    text = element_text(size = 20),
    plot.margin = unit(c(0, 0.75, 0, 0), "inches"),
    legend.position = "none",
    panel.grid.major.x = element_line(color = "grey", size = 0.3, linetype = 2)
  ) +
  scale_x_continuous(
    breaks = c(1990, 2020, 2050, 2100), 
    labels = c("1990", "2020", "2050", "2100")
  ) +
  # Separate geom_curve() layers for each curve segment
  geom_curve(aes(x = 1990, y = -5000, xend = 2019, yend = 4000), inherit.aes = FALSE, curvature = 0.2, color = "grey") +
  geom_curve(aes(x = 2021, y = -5000, xend = 2049, yend = 4000), inherit.aes = FALSE, curvature = 0.2, color = "grey") +
  geom_curve(aes(x = 2051, y = -5000, xend = 2100, yend = 4000), inherit.aes = FALSE, curvature = 0.2, color = "grey") +
  scale_color_manual(values = pal) +   
  scale_y_continuous(
    breaks = c(0, 200000, 400000, 600000, 800000), 
    labels = c("0", "-", "400M", "-", "800M"),
    limits = c(0, 800000)
  )

```



```{r labels, include=FALSE}

countries = c(
  "South Africa",
  "Ghana", 
  "Nigeria", 
  "Tanzania", 
  "Ethiopia",
  "Uganda",
  "Malawi",
  "Niger"
  )

regions = c(
  "**Average**", 
  '**1.-** Eastern Africa <br>', 
  '**2.-** Southern Africa <br>', 
  '**3.-** Western Africa <br>'
  )

counn = rep(countries, 4)

var_sum = c(
  "govtexpgdp", 
  "oopexp", 
  "uhcidx",
  "socexpnohealth", 
  "lifeexpsixtytotal",
  "pensioncoverage",
  "hospbeds",
  "physicians",
  "country", 
  "cou"
  )

ids = c("gender", "age_group5")

#colo = c(
#  "#000C66", 
#  "#800000", 
#  "#8eb67d"
#  )

colo = c(
  "black", 
  "#3f3f3f", 
  "#8eb67d"
  )

labeller_environ <- c( 
  'lifeexpsixtytotal'="**A.-** Remaining Life<br>Expectancy At age 60<br>(Years)<br>",
  'socexpnohealth'="**B.-** Social Protection<br> Expenditure on Elderly<br>(Percentage of GDP)<br>",
  'pensioncoverage'="**C.-** Pension<br>Coverage<br>(Percentage)<br>"
)


var_env <- c(
   'lifeexpsixtytotal',
   'socexpnohealth',
   'pensioncoverage'
 )
 
measures_labs <- c(
  "A) Functional\nLimitations\n(Proportion)",
  "B) Illness & Injury\n(Proportion)",
  "C) Stopped Activities\n(Proportion)", 
  "D) Depression\nOr Psych Distress\n(Proportion)", 
  "E) Employment\nStatus\n(Proportion)",
  "F) Weekly\nEmployment Status\n(Hours)",
  "G) Unmarried \n (Proportion)",
  "H) Living alone\n(Proportion)", 
  "I) Urban Status\n(Proportion)",
  "J) Health\nInsurance\n(Proportion)"
)

measures = c(
  "disability", 
  "ill_inj", 
  "ill_inj_stopactivity", 
  "depressed", 
  "work_any", 
  "work_hrs",
  "notmarried", 
  "lives_alone", 
  "urban", 
  "healthinsurance_ever"
  )

measures_labs_agg <- c(
  "**A.-** Functional<br>Limitations<br>",
  "**B.-** Illness & Injury<br>",
  "**C.-** Stopped Activities<br>", 
  "**D.-** Depression<br> Or Psych Distress<br>", 
  "**E.-** Employment Status<br>",
  "**F.-** Weekly Employed <br> Hours / 40<br>",
  "**G.-** Unmarried<br>",
  "**H.-** Living alone<br>", 
  "**I.-** Urban Status<br>",
  "**J.-** Health<br>Insurance<br>"
)
limitations <- c(
  "diff_seei", 
  "diff_hear",
  "diff_reme",
  "diff_walk_clim",
  "diff_self_care",
  "diff_comm"
)

limitations_labs <- c(
  "**A.-** Seeing<br>",
  "**B.-** Hearing<br>",
  "**C.-** Remembering<br>",
  "**D.-** Walking or Climbing<br>",
  "**E.-** Self Care<br>",
  "**F.-** Communicating<br>"
)

bre_age = c(
  "20",
  "25",
  "30", 
  "35",
  "40", 
  "45",
  "50",
  "55",
  "60", 
  "65", 
  "70", 
  "75",
  "80"
  )

lab_age = c(
  "20", 
  "", 
  "", 
  "", 
  "40",
  "", 
  "",  
  "",
  "60",
  "", 
  "", 
  "", 
  "80+"
  )

labeller_health <- c(
  'uhcidx'="**A.-** Health Care<br> Service Coverage<br>(Index)<br>",
  'oopexp'="**B.-** 100 - Out of Pocket<br>Health Expenditure<br>(Percentage)<br>",
  `govtexpgdp`="**C.-** Gov. Health<br>Expenditure<br>(Percentage of GDP)<br>",
  'hospbeds'="**D.-** N° of Hospital Beds<br>Per 1,000<br>(Count)<br>",
  'physicians'="**E.-** N° of Physicians<br>Per 1,000<br>(Count)<br>"
)

var_hea = c(
  'uhcidx',
  'oopexp', 
  'govtexpgdp', 
  'hospbeds', 
  'physicians'
  )

```

```{r functions, include=FALSE}
trans_input_gende <- function(
    data,
    var_vec,
    var_nam="condition",
    val_nam="measurement"
){
  data$gen <- data$female
  data$female <- as.factor(data$female)
  data$age_group5 <- as.factor(data$age_group5)
  data = data %>% 
      mutate(
        female = case_when(
        female==0
         ~ 'Male',
        female ==1
        ~ 'Female',
        TRUE ~ NA)
      )
  data$gender <- as.factor(data$female)
  
  data = melt(data,
      id.vars=ids,
      measure.vars=var_vec,
      variable.name=var_nam,
      value.name=val_nam
  )
  
  data <- data %>% 
    group_by(age_group5, gender) %>% 
    filter(!age_group5  %in% c('0', '5', '10', '15'))
  return (data)
}
  


trans_input_count <- function(
    data,
    var_vec,
    ids = c("country", "age_group5"),
    var_nam="condition",
    val_nam="measurement"
 
){
  data$age_group5 <- as.factor(data$age_group5)
  data$work_hrs = data$work_hrs/40
  data = melt(data,
      id.vars=ids,
      measure.vars=var_vec,
      variable.name=var_nam,
      value.name=val_nam
  )
  
  data <- data %>% 
    group_by(age_group5, country) %>% 
    filter(!age_group5  %in% c('0', '5', '10', '15')) %>% 
    mutate(
      country = case_when(
        country == 'eth'
         ~ 'Ethiopia',
        country == 'mlw'
         ~ 'Malawi',  
        country == 'nga'
         ~ 'Nigeria',  
        country == 'tza'
         ~ 'Tanzania',  
        country == 'gha'
         ~ 'Ghana', 
        country == 'saf'
         ~ 'South~Africa',
        country == 'uga'
         ~ 'Uganda',
        country == 'niger'
         ~ 'Niger',
        country == 'ssa'
         ~ '**Average**',
        TRUE ~ NA)
    )
  return (data)
}

theme_spac <- function(
    size_text=18,
    size_title=23,
    size_legend=20,
    color="#344771"
){
  top = theme(
    axis.title.x = element_blank(),
    panel.background = element_blank(),
    plot.background = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    strip.background=element_rect(fill = "transparent", color = NA),
    axis.text = element_text(color = color, size = size_text, hjust = 0),
    axis.text.y = element_blank(),
    legend.background = element_blank(),
    legend.box.background = element_blank(),
    legend.position="bottom", 
    axis.line.x.bottom =element_line(),
    axis.line.x.top =element_line(),
    legend.text = element_text(
      margin = margin(t = size_legend, b = size_text, unit = "pt"),
      size=size_legend
      ),
    legend.key.size = unit(3.5,"line"), 
    legend.key = element_blank(),
    text = element_text(size = size_text, color=color), 
    strip.text = element_markdown(color = color, size=size_title),
    axis.title.y = element_text(angle = 0),
    panel.spacing = unit(1.5, "lines"),
    plot.margin = margin(, 1.2, , , "cm")

    )
}


theme_top_a <- function(
    size_text=35,
    size_title=42,
    size_legend=42,
    color="#344771"
){
  top = theme(
    axis.title.x = element_blank(),
    strip.background=element_rect(fill = "transparent", color = NA),
    panel.grid.major = element_line(linetype="dashed"),
    axis.text = element_text(color = color, size = size_title, hjust = 0),


    axis.text.x = element_blank(),
    legend.position="top", 
    legend.justification = "right",
    axis.ticks.x = element_blank(),
    legend.title=element_blank(),
    legend.text = element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend,
      color = color
      ),
    legend.key.size = unit(6,"line"), 

    text = element_text(size = size_text, color=color), 
    strip.text = element_markdown(color = color, size=size_title),
    axis.title.y = element_text(angle = 0, size=size_title),
    panel.spacing.x = unit(5, "lines"),
    panel.spacing.y = unit(7, "lines"),
    plot.margin = margin(, 2, , , "cm")

    )

  return (top)
}

theme_top <- function(
    size_text=35,
    size_title=42,
    size_legend=42,
    color="#344771"

){
  top = theme(
    axis.title.x = element_blank(),
    strip.background=element_rect(fill = "transparent", color = NA),
    panel.grid.major = element_line(linetype="dashed"),
    axis.text = element_text(color = color, size = size_title, hjust = 0),


    #axis.text.x = element_blank(),
    legend.position="top", 
    legend.justification = "right",
    axis.ticks.x = element_blank(),
    legend.title=element_blank(),
    legend.text = element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend,
      color = color
      ),
    legend.key.size = unit(6,"line"), 

    text = element_text(size = size_text, color=color), 
    strip.text = element_markdown(color = color, size=size_title),
    axis.title.y = element_markdown(angle = 0, size=size_title),
    panel.spacing.x = unit(5, "lines"),
    panel.spacing.y = unit(7, "lines"),
    plot.margin = margin(, 2, , , "cm")

    )

  return (top)
}


theme_middle <- function(
    size_text=35,
    size_title=42,
    color="#344771"

){
  middle = theme(
    strip.background = element_blank(),
    axis.text.y = element_text(color = color, size = size_title, hjust = 0),
    plot.background=element_rect(fill = "transparent", color = NA),
        panel.grid.major = element_line(linetype="dashed"),

    strip.text.x = element_blank(), 
    
    text = element_text(size = size_text, color=color), 
    legend.position="none",
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_text(angle = 0, size=size_title),
    panel.spacing.x = unit(5, "lines"),
    panel.spacing.y = unit(7, "lines"),
    plot.margin = margin(, 2, , , "cm")
    )

  return (middle)
}


theme_bottom <- function(
    size_text=38,
    size_title=42,
    size_legend=32,
    color="#344771"
){
  bottom = theme(
    strip.background = element_blank(),
    plot.background=element_rect(fill = "transparent", color = NA),
    axis.text = element_text(color = color, size = size_title, hjust = 0),
    strip.text.x = element_blank(), 
    legend.position="bottom", 
    legend.justification = "left",
    legend.title=element_blank(),
        panel.grid.major = element_line(linetype="dashed"),

    legend.text = element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend,
      color = color
      ),
    legend.key.size = unit(6,"line"), 
    
    text = element_text(size = size_text, color=color),
    axis.title.y = element_text(angle = 0, size=size_title),
    axis.title.x = element_text(size=size_title, color=color, face = "bold"),
    panel.spacing.x = unit(5, "lines"),
    panel.spacing.y = unit(7, "lines"),
    plot.margin = margin(, 2, , , "cm")
    )

  return (bottom)
}

get_count <- function(
    var
){
  ssa0 <- ssa
  ssa0$country = ''
  ssa0$region = "**Average**"
  ssa <- rbind(ssa0, ssa)
  annot0 = ssa %>% 
  filter(
    age==20 & gender=='Male'
    ) %>% 
  group_by(age_group5, country, gender, region) %>% 
  summarise(vari = mean(get(var), na.rm=TRUE))
  
  

  annot1 = ssa %>% 
    filter(
      age>=20 & !is.na(gender) 
      ) %>% group_by(country, gender) %>% 
    summarise(
      n = sum(!is.na(country)&!is.na(get(var)))
      ) %>% 
    group_by(country) %>% 
    summarise(n = paste0("N=", comma(sum(n), digits = 0)))
  
  count <- merge(annot0, annot1, by="country")
  
  return (count)
}


fac_row_popu <- function(
    forma_theme,
    colors=c("#8eb67d","#000C66"),
    breaks=c("20","25","30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80"),
    labels=c("20", "", "", "", "40", "", "",  "", "60", "", "", "", "80+"),
    size_count=12

){
  
  dat = get_count("gender")
  subsah <- ssa
  subsah$country <- ''
  subsah$region <-  "**Average**"
  ssa <- rbind(ssa, subsah)
  ssa = ssa %>% filter(!age_group5  %in% c('0', '5', '10', '15'))

  graph <- ssa %>%
    filter(age>=20  & !is.na(gender))%>%  ggplot(
      aes(x = age_group5, fill=gender)
      ) + 
    theme_minimal() +
    geom_bar(binwidth = 0.5, color = "white", position = "dodge") +
    facet_nested(~factor(region, levels=regions) +country, scales='free_y', space="free_y", nest_line = element_line(linetype = 1)) +
 force_panelsizes(cols = c(1, rep(0.85, 7))) +
    scale_fill_manual("legend", values = c("Female" = "#8eb67d", "Male" = "#000C66"))+
    geom_text(
      data = dat, 
      label = dat$n,
      aes(label = paste0("N=", n), y = Inf, x  = -Inf),
      vjust = 1,
      colour="#14213D",
      hjust = -0.2,
      size = size_count
      ) +
    forma_theme
  
    #graph = graph + geom_rect(
    #    aes(xmin = "60", xmax = Inf, ymin = -Inf, ymax = Inf),
    #    alpha = 0.01,
    #    fill = "#8eb67d"
    #      )
  return (graph)
}

fac_row__<- function(
    var,
    forma_theme,
    weighted=TRUE,
    colors=c("#8eb67d","#000C66"),
    size_count=12
){
  
  dat = get_count(var)
  
  if (weighted) {
    data <- ssa %>% 
      filter(
        age>=20 & !is.na(gender) 
        ) %>% 
      group_by(age_group5, country, gender, region) %>% 
      summarise(vari = weighted.mean(get(var), weights_survey, na.rm=TRUE)) 
    data$age_group5 <- as.factor(data$age_group5)

    ssa_agg = ssa_agg %>% mutate(vari = get(var))
    ssa_agg = ssa_agg %>% 
        mutate(
          female = case_when(
          female==0
           ~ 'Male',
          female ==1
          ~ 'Female',
          TRUE ~ NA),
          work_hrs = case_when(
            work_hrs>=140 & work_hrs<=168 ~ 140,
            work_hrs>168 ~ NA,
            TRUE ~ work_hrs
            )
          )
    ssa_agg$gender <- as.factor(ssa_agg$female)
    ssa_agg <- ssa_agg %>% 
      filter(
        !is.na(gender) 
        ) 
    ssa_agg$age_group5 <- as.factor(ssa_agg$age_group5)
    ssa_agg = ssa_agg %>% filter(!age_group5  %in% c('0', '5', '10', '15'))

    ssa_agg$country = ''
    ssa_agg$region =  "**Average**"
    
    data=bind_rows(data,ssa_agg)
    
  } else {
    data <- ssa %>% 
      filter(
        age>=20 & !is.na(gender) 
        ) %>% 
      group_by(age_group5, country, gender, region) %>% 
      summarise(vari = mean(get(var), na.rm=TRUE))
    data$age_group5 <- as.factor(data$age_group5)

    ssa_agg_non$gender <- as.factor(ssa_agg_non$female)
    ssa_agg_non <- ssa_agg_non %>% 
      filter(
        !is.na(gender) 
        ) 
    ssa_agg_non = ssa_agg_non %>% mutate(vari = get(var))
    ssa_agg_non = ssa_agg_non %>% 
        mutate(
          female = case_when(
          female==0
           ~ 'Male',
          female ==1
          ~ 'Female',
          TRUE ~ NA),
          work_hrs = case_when(
            work_hrs>=140 & work_hrs<=168 ~ 140,
            work_hrs>168 ~ NA,
            TRUE ~ work_hrs
            )
          )
    ssa_agg_non$gender <- as.factor(ssa_agg_non$female)
    ssa_agg_non <- ssa_agg_non %>% 
      filter(
        !is.na(gender) 
        ) 
    ssa_agg_non$age_group5 <- as.factor(ssa_agg_non$age_group5)
    
    ssa_agg_non$country = ''
    ssa_agg_non$region =  "**Average**"
    ssa_agg_non = ssa_agg_non %>% filter(!age_group5  %in% c('0', '5', '10', '15'))

    data=bind_rows(data,ssa_agg_non)
  
  }
  
  graph = ggplot(
      data,
      aes(x = age_group5, y = vari, colour = gender, group=gender)
      ) + 
    theme_minimal() +
    geom_line(size = 3, aes(linetype=gender)) +
        facet_nested(~factor(region, levels=regions) +country, scales='free_y', space="free_y", nest_line = element_line(linetype = 1)) +     force_panelsizes(cols = c(1, rep(0.85, 7))) +

   scale_color_manual(values = colors) +
    
    scale_linetype_manual(values=c("solid", "longdash"))  +
    geom_text(
      data = dat, 
      label=dat$n,
      aes(label = paste0("N=", n), y = Inf, x  = -Inf),
      vjust = 1,
      colour="#14213D",
      hjust = -0.2,
      size = size_count
      ) +
      geom_rect(
        aes(xmin = "60", xmax = Inf, ymin = -Inf, ymax = Inf),
        alpha = 0.005,
        fill = "#8eb67d"
          ) +
    forma_theme

  return (graph)
}


fac_row <- function(
    var,
    forma_theme,
    weighted=TRUE,
    colors=c("#8eb67d","#000C66"),
    size_count=12
){
  
  dat = get_count(var)
  
  if (weighted) {
    data <- ssa %>% 
      filter(
        age>=20 & !is.na(gender) 
        ) %>% 
      group_by(age_group5, country, gender, region) %>% 
      summarise(vari = weighted.mean(get(var), weights_survey, na.rm=TRUE)) 
    data$age_group5 <- as.factor(data$age_group5)

    ssa_agg = ssa_agg %>% mutate(vari = get(var))
    ssa_agg = ssa_agg %>% 
        mutate(
          female = case_when(
          female==0
           ~ 'Male',
          female ==1
          ~ 'Female',
          TRUE ~ NA),
          work_hrs = case_when(
            work_hrs>=140 & work_hrs<=168 ~ 140,
            work_hrs>168 ~ NA,
            TRUE ~ work_hrs
            )
          )
    ssa_agg$gender <- as.factor(ssa_agg$female)
    ssa_agg <- ssa_agg %>% 
      filter(
        !is.na(gender) 
        ) 
    ssa_agg$age_group5 <- as.factor(ssa_agg$age_group5)
    ssa_agg = ssa_agg %>% filter(!age_group5  %in% c('0', '5', '10', '15'))

    ssa_agg$country = ''
    ssa_agg$region =  "**Average**"
    
    data=bind_rows(data,ssa_agg)
    
  } else {
    data <- ssa %>% 
      filter(
        age>=20 & !is.na(gender) 
        ) %>% 
      group_by(age_group5, country, gender, region) %>% 
      summarise(vari = mean(get(var), na.rm=TRUE))
    data$age_group5 <- as.factor(data$age_group5)

    ssa_agg_non$gender <- as.factor(ssa_agg_non$female)
    ssa_agg_non <- ssa_agg_non %>% 
      filter(
        !is.na(gender) 
        ) 
    ssa_agg_non = ssa_agg_non %>% mutate(vari = get(var))
    ssa_agg_non = ssa_agg_non %>% 
        mutate(
          female = case_when(
          female==0
           ~ 'Male',
          female ==1
          ~ 'Female',
          TRUE ~ NA),
          work_hrs = case_when(
            work_hrs>=140 & work_hrs<=168 ~ 140,
            work_hrs>168 ~ NA,
            TRUE ~ work_hrs
            )
          )
    ssa_agg_non$gender <- as.factor(ssa_agg_non$female)
    ssa_agg_non <- ssa_agg_non %>% 
      filter(
        !is.na(gender) 
        ) 
    ssa_agg_non$age_group5 <- as.factor(ssa_agg_non$age_group5)
    
    ssa_agg_non$country = ''
    ssa_agg_non$region =  "**Average**"
    ssa_agg_non = ssa_agg_non %>% filter(!age_group5  %in% c('0', '5', '10', '15'))

    data=bind_rows(data,ssa_agg_non)
  
  }
  
  graph = ggplot(
      data,
      aes(x = age_group5, y = vari, colour = gender, group=gender)
      ) + 
    theme_minimal() +
    geom_line(size = 3, aes(linetype=gender)) +
    facet_nested(~factor(region, levels=regions) +country, scales='free_y', space="free_y")+    scale_color_manual(values = colors) +
     force_panelsizes(cols = c(1, rep(0.85, 7))) +

    scale_linetype_manual(values=c("solid", "longdash"))  +
    geom_text(
      data = dat, 
      label=dat$n,
      aes(label = paste0("N=", n), y = Inf, x  = -Inf),
      vjust = 1,
      colour="#14213D",
      hjust = -0.2,
      size = size_count
      ) +
      geom_rect(
        aes(xmin = "60", xmax = Inf, ymin = -Inf, ymax = Inf),
        alpha = 0.005,
        fill = "#8eb67d"
          ) +
    forma_theme

  return (graph)
}


theme_top_count <- function(
    size_text=35,
    size_title=42,
    size_legend=32,
    color="#344771"
){
  top = theme(
    legend.position="top", 
    legend.justification="right",
    legend.title=element_blank(),
    legend.text=element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend
      ),
    legend.key.size = unit(6,"line"), 
    strip.background=element_rect(fill = "transparent", color = NA),
    axis.text = element_markdown(color = color, size = size_text),
    text = element_text(size = size_text), 
    strip.text = element_markdown(color = color, size=size_text),
    #panel.grid.minor.x = element_blank(),
    panel.grid.major = element_line(linetype="dashed"),

    axis.title = element_text(margin = margin(l = 20, b=20), color=color, size=size_text, face='bold'),
    panel.spacing.x = unit(5, "lines"),
    panel.spacing.y = unit(3, "lines")
    )

  return (top)
}

fac_row_agg_count_out <- function(
    data,
    vars,
    labels,
    forma_theme,
    size_count=10
){
  
  condition.labs <- labels
  names(condition.labs) <- vars
  levels(data$age_group5) <- c(levels(data$age_group5),'')
  levels(data$age_group5) <- c(levels(data$age_group5),'')
  f_labels <- data.frame(condition = c("urban", 
  "work_any", 
  "work_hrs",
  "notmarried", 
  "lives_alone", 
  "ill_inj", 
  "ill_inj_stopactivity", 
  "depressed", 
  "disability"), country = c( "Average", "", "", "", "", "", "", "", ""),
  label = c( "Average", "", "", "", "", "", "", "", "Average"))
  f_labels$condition = factor(f_labels$condition)

  graph <-data %>%  
    filter(condition!='healthinsurance_ever') %>% 
    mutate(label = ifelse(country== "**Average**", country, NA)) %>%
    ggplot(
      aes(x = age_group5, y = measurement, colour = I(ifelse(country ==  "**Average**", "#050A30", "#D3D3D3")), group=country)
      ) +
    facet_wrap(
      . ~condition, 
      ncol = 3, 
      labeller = labeller(condition=condition.labs)#,
      #scales='free_y'

      ) +
    geom_rect(
      aes(xmin = "60", xmax = "80", ymin = -Inf, ymax = Inf),
      #alpha = 0.009,
      alpha=0.006,
      fill="#344771"
      #fill = "#000C66"
        ) +
    #geom_dl(aes(label = label), method = list(dl.trans(x = x + 0.05), "last.points", cex = 0.8)) +
    theme_minimal() +
    #geom_line(size = 1) +
    geom_line(size=1.1) +
    geom_line(data = filter(data, (country ==  "**Average**" & condition!='healthinsurance_ever')), size = 2)+#, linetype="dashed")+
  geom_text(x = "40", y = 0.25, aes(label = label), data = f_labels, size=9, color="#050A30")+

    scale_fill_manual(values = c("#D3D3D3")) +
    forma_theme
  
  
  return (graph)
}

 
fac_row_agg_count_dis <- function(
    data,
    vars,
    labels,
    forma_theme,
    size_count=10
){
  condition.labs <- labels
  names(condition.labs) <- vars
  levels(data$age_group5) <- c(levels(data$age_group5),'')
  levels(data$age_group5) <- c(levels(data$age_group5),'')
  f_labels <- data.frame(condition = c("diff_seei", 
  "diff_hear",
  "diff_reme",
  "diff_walk_clim",
  "diff_self_care",
  "diff_comm"), country = c( "Average", "", "", "", "", ""),
  label = c( "Average", "", "", "", "",  "Average"))
  f_labels$condition = factor(f_labels$condition)

  graph <-data %>%  
    filter(str_detect(condition, 'diff')) %>% 
    mutate(label = ifelse(country==  "**Average**", country, NA)) %>%
    ggplot(
      aes(x = age_group5, y = measurement, colour = I(ifelse(country ==  "**Average**", "#050A30", "#D3D3D3")), group=country)
      ) + 
    facet_wrap(
      . ~condition, 
      ncol = 3, 
      labeller = labeller(condition=condition.labs)#,
      #scales='free_y'

      ) +
    geom_rect(
      aes(xmin = "60", xmax = "80", ymin = -Inf, ymax = Inf),
      alpha=0.006,
      fill="#344771"
        ) +
    theme_minimal() +
    geom_line(size=1.1) +
    geom_line(data = filter(data, (country ==  "**Average**" & str_detect(condition, 'diff'))), size = 2)+
  geom_text(x = "40", y = 0.15, aes(label = label), data = f_labels, size=9, color="#050A30")+

    scale_fill_manual(values = c("#D3D3D3")) +

    forma_theme
  
  
  return (graph)
}

graph_agg_data_main <- function(
      weighted=TRUE,
      breaks=bre_age,
      labels=lab_age
      ){
  a <- fac_row_popu(theme_top()) + 
    labs(y = "**Observations<br>(Count)**", face='bold') +
    scale_x_discrete(
      breaks=breaks,
      labels=labels,
      position="bottom"
      ) + 
    scale_y_continuous(
      breaks=c(0, 20000, 40000), 
      limits = c(0, 50000), 
      labels = c('0', '20K', '40K')
      )
  
   b <- fac_row("disability", theme_middle(), weighted) + 
    ylim(0, 1) + 
    labs(y = "           Functional     \n           Limitations     \n           (Proportion)     ", x = "Age")+
    scale_x_discrete(
        breaks=breaks,
        labels=labels,
        position="top"
        )+scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
    theme(legend.position = "none")
   c <- fac_row("ill_inj", theme_middle(), weighted) + 
    ylim(0, 1) + 
    labs(y = "Illness & Injury\n(Proportion)")+ 
    scale_x_discrete(
        breaks=breaks,
        labels=labels,
        position="top"
        )+scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
   d <- fac_row("ill_inj_stopactivity", theme_middle(), weighted) +
    ylim(0, 1) + labs(y = "     Stopped Activities\n(Proportion)")+
    scale_x_discrete(
        breaks=breaks,
        labels=labels,
        position="top"
        )+scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
  e <- fac_row("depressed", theme_middle(), weighted) + 
    ylim(0, 1) +
    labs(y = "  Depression\n  Or Psych Distress\n  (Proportion)", x = "Age")+ 
    scale_x_discrete(
        breaks=breaks,
        labels=labels,
        position="top"
        ) +scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
  
  f <- fac_row("work_any", theme_middle(), weighted) +
    ylim(0, 1) +
    labs(y = "Employment\nStatus\n(Proportion)")+ 
    scale_x_discrete(
        breaks=breaks,
        labels=labels,
        position="top"
        ) +scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
  g <- fac_row("work_hrs", theme_middle(), weighted) + 
    labs(y = "Weekly\nEmployment Status\n(Hours)", x = "Age")+ 
    scale_x_discrete(
        breaks=breaks,
        labels=labels,
        position="top"
        ) + scale_y_continuous(breaks=c(0,20, 40), limits = c(0, 50), labels = c('0', '-', '40'))
  h <- fac_row("notmarried", theme_middle()) + 
    ylim(0, 1) + 
    labs(y = "Unmarried\n(Proportion)")+ 
    scale_x_discrete(
        breaks=breaks,
        labels=labels,
        position="top"
        ) +scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
  i <- fac_row("lives_alone", theme_middle(), weighted) + 
    ylim(0, 1) + 
    labs(y = "Living alone\n(Proportion)", x = "Age")+ 
    scale_x_discrete(
        breaks=breaks,
        labels=labels,
        position="top"
        ) + scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
  j <- fac_row("urban", theme_bottom(), weighted) +
    ylim(0, 1) +
    labs(y = " Urban Status\n(Proportion)", x = "\n \n\nAge", color="#344771") + 
    scale_x_discrete(
        breaks=breaks,
        labels=labels,
        position="bottom"
        )+theme(legend.position = "none")+scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))

  plot_grid(
    a, b, c,  d, e,  f,  g, h,  i,  j,  
    rel_heights = c(9.5, 5,  5, 5, 5, 5,5, 5, 5,7.5),
    ncol = 1, 
    nrow = 10, 
    align = "v", 
    labels = c("*", "A.-", "B.-", "C.-","D.-", "E.-", "F.-", "G.-", "H.-", "I.-"),
    label_size = 38,
    label_colour = "#14213D"
    )
}
```




```{r}
main_outco <- function(
  vars,
  labs,
  dat = dat_long,
  high = high_inco,
  sub = sub_sahar_inco,
  low = low_middle_inco,
  size_line = 1.1
) {
  graph = dat %>% 
    filter(variable %in% vars) %>% 
    ggplot(aes(reorder(country, order), value)) + 
    geom_bar(stat = "identity", fill = "white", color = "#1F271B", width = 0.85, size = 0.5) + 
    facet_grid(~factor(variable, levels = vars), scales = "free_x", labeller = as_labeller(labs)) +
    ylab("") + 
    xlab("") + 
    coord_flip() + 
    geom_hline(
      data = sub %>% filter(variable %in% vars), 
      aes(yintercept = value, color = "Sub-Saharan African Countries", linetype = "Sub-Saharan African Countries"),
      size = size_line, color = "#8eb67d"
    ) +
    geom_hline(
      data = low %>% filter(variable %in% vars), 
      aes(yintercept = value, linetype = "Low-middle Income Countries"),
      size = size_line, color = "#686868"
    ) +
    geom_hline(
      data = high %>% filter(variable %in% vars), 
      aes(yintercept = value, color = "High Income Countries", linetype = "High Income Countries"),
      size = size_line, color = "black"
    ) +
    guides(color = guide_legend(title = "Regional\nAverages", reverse = TRUE)) +
    scale_linetype_manual(name = "Regional\nAverages", values = c(1, 2, 1), 
                          guide = guide_legend(title = "Regional\nAverages", reverse = TRUE, 
                                               override.aes = list(color = c("#8eb67d", "#686868", "black")))) +
    theme_minimal() +
    theme_spac() +
    
    # Assign labels to the countries in the plot
    geom_text(
      aes(label = ifelse(country %in% c("South Africa", "Malawi", "Niger", "Tanzania", "Ghana", "Ethiopia", "Uganda", "Nigeria"), country, ""),
          hjust = ifelse(country == "South Africa", 0.9, -0.05)), 
      color = "#344771", 
      size = 4.5
    ) 
    
  return(graph)
}
```



```{r data_trans, include=FALSE}
outcomes_weighted_country = trans_input_count(
  subsaharan_weighted, measures
  ) 

outcomes_nonweighted_country = trans_input_count(
  subsaharan_nonweighted, measures
  ) 

outcomes_weighted_country_lim = trans_input_count(
  subsaharan_weighted, limitations
  )  


outcomes_nonweighted_country_lim = trans_input_count(
  subsaharan_nonweighted, limitations
  ) 
```

```{r}

disabili_weighted_gender = trans_input_gende(
  ssa_agg, limitations
  )  
disabili_nonweight_gender = trans_input_gende(
  ssa_agg_non, limitations
  ) 
ssa$gen <- ssa$female
ssa$female <- as.factor(ssa$female)

ssa$age_group5 <- as.factor(ssa$age_group5)

ssa = ssa %>% 
    mutate(
      female = case_when(
      female==0
       ~ 'Male',
      female ==1
      ~ 'Female',
      TRUE ~ NA), 
      country = case_when(
        country == 'eth'
         ~ 'Ethiopia',
        country == 'mlw'
         ~ 'Malawi',  
        country == 'nga'
         ~ 'Nigeria',  
        country == 'tza'
         ~ 'Tanzania',  
        country == 'gha'
         ~ 'Ghana', 
        country == 'saf'
        ~ 'South Africa',
        country == 'uga'
         ~ 'Uganda',
        country == 'niger'
         ~ 'Niger',
        TRUE ~ NA),
      work_hrs = case_when(
        work_hrs>=140 & work_hrs<=168 ~ 140,
        work_hrs>168 ~ NA,
        TRUE ~ work_hrs
        ),
      region = case_when(
        country %in% c('Ethiopia', 'Tanzania', 'Uganda')
         ~ '**1.-** Eastern Africa <br>',  
        country  %in% c('Ghana', 'Nigeria', 'Niger')
         ~ '**3.-** Western Africa <br>',
        TRUE ~ '**2.-** Southern Africa <br>'
      ),
      depressed = case_when(
        country=='Nigeria'
         ~ NA,
        TRUE ~ depressed
      ))
ssa$gender <- as.factor(ssa$female)
```

```{r}
projections['1990'] =projections$pop_60plus_1990
projections['2020'] =projections$pop_60plus_2020
projections['2050'] =projections$pop_60plus_2050

proj_pop = projections %>% select(
  country, 
  '1990',
  '2020', 
  '2050'
)

proj_pop = rapply(
  object = proj_pop,
  f = round,
  classes = "numeric",
  how = "replace",
  digits = 0
  ) 

proj_pop = gather(
  proj_pop,
  measurement,
  value,
  '1990':'2050',
  factor_key=TRUE
  )

proj_pop = proj_pop %>% 
  filter(
    country %in% countries
    )

proj_pop = proj_pop %>% mutate(
  value=value
) %>%  mutate(across(c('value'), round, 1))

```



```{r}

dat = dat %>% select(
  'country', 
  'physicians', 
  'hospbeds', 
  'govtexpgdp', 
  'oopexp', 
  'pensioncoverage',
  'socexpnohealth',
  "lifeexpsixtytotal",
  'uhcidx'
  )

dat <- dat[order(dat$govtexpgdp, decreasing=TRUE),]

dat$cou = ifelse(
  (dat$country %in% countries), 1, 0
  )

dat$oopexp=(100-dat$oopexp)

dat_1 = dat %>% filter(cou!=0)

dat_1 = dat_1 %>% select(
  var_sum
  )

dat_long = gather(
  dat_1, 
  variable, 
  value, 
  govtexpgdp:physicians, 
  factor_key=TRUE
  )

dat_long = dat_long %>%                         
  mutate(order=
    case_when(
        country == 'South Africa'
         ~ 1,
        country == 'Ghana'
         ~ 2,  
        country == 'Nigeria'
         ~ 3,  
        country == 'Tanzania'
         ~ 4,  
        country == 'Ethiopia'
         ~ 5,  
        country == 'Uganda'
         ~ 6,
        country == 'Malawi'
         ~ 7,
        country == 'Niger'
         ~ 8        
        ))

dat_long[
  with(dat_long, order(variable, order)),
]

dat_0 = dat %>% filter(cou!=1)

dat_0 = dat_0 %>% select(
  var_sum
  )

dat_long_0 = gather(
  dat_0, 
  variable, 
  value, 
  govtexpgdp:physicians, 
  factor_key=TRUE
  )

dat_long_0 = dat_long_0 %>%
  mutate(order = row_number())

high_inco = dat %>%
  filter(str_detect(country, 'HIC')) %>% 
  select(-cou)

low_middle_inco =  dat %>%
  filter(str_detect(country, 'LMICs_nonSSA')) %>% 
  select(-cou)

sub_sahar_inco =  dat %>%
  filter(country=='Sub-Saharan Africa') %>% 
  select(-cou)

high_inco = gather(
  high_inco,
  variable, 
  value, 
  physicians:uhcidx, 
  factor_key=TRUE
)

low_middle_inco = gather(
  low_middle_inco,
  variable, 
  value, 
  physicians:uhcidx, 
  factor_key=TRUE
)
  
sub_sahar_inco = gather(
  sub_sahar_inco,
  variable, 
  value, 
  physicians:uhcidx, 
  factor_key=TRUE
)
```



```{r pop_grow, echo=FALSE, fig.height=6, fig.width=5, dev = c("png"), dpi=100}
# Figure 1: Panel B: Over-60 population (m.)
proj_pop = proj_pop %>% mutate(
  measurement = factor(measurement, levels = c('1990', '2020', '2050'), ordered = TRUE)
)

newggslopegraph(
  dataframe = proj_pop,
  Times = measurement,
  Measurement = value,
  Grouping = country,
  Title = "",
  SubTitle = "",
  Caption = NULL,
  DataTextSize = 4,
  YTextSize = 4,
  XTextSize = 15,
  TitleTextSize = 10,
  SubTitleTextSize = 2,
  LineThickness = 1,
  LineColor = rep("#8eb67d", nrow(proj_pop)),  # Repeating the color for each row
  WiderLabels = TRUE,
  ThemeChoice = "minimal"
  )
```


```{r ov60_pop, echo=FALSE, fig.height=7.5, fig.width=18, dev = c("png"), dpi=100}
# Figure 2: Projected Population Growth and Dependency Ratios
# Panels A & B
fig1a | fig1b  
```




```{r ov60_growth, echo=FALSE, fig.height=7.5, fig.width=18, dev = c("png"), dpi=100}
# Figure 2: Projected Population Growth and Dependency Ratios
# Panels C & D
fig1c | fig1d
```

```{r ov60_dep_rat, echo=FALSE, fig.height=7.5, fig.width=18, dev = c("png"), dpi=100}
# Figure 2: Projected Population Growth and Dependency Ratios
# Panels E & F
wrap_elements(panel = depratov60  + oldageratov60 ) +
  labs(tag = "**Year**") +
  theme(
    plot.tag = element_markdown(size=20, color="#344771"),
    plot.tag.position = "bottom"
  )
```


```{r hea_care, echo=FALSE, fig.height=7.5, fig.width=15, dev = c("png"), dpi=100}
# Figure 7: Social Protection across Selected Sub-Saharan African Countries
main_outco(
  vars=var_env,
  labs=labeller_environ
  )

```

```{r environ, echo=FALSE, fig.height=7.5, fig.width=18, dev = c("png"), dpi=100}
#Figure 8: Health Spending and Health Care Capacity across Selected Sub-Saharan African Countries
main_outco(
  vars=var_hea,
  labs=labeller_health
  )
```




\begin{landscape}
```{r outcomes_aggregate_weighted, fig.cap="Employment. Age Group and Gender.", echo=FALSE,  fig.height=25, fig.width=25, dev = c("png"), dpi=100}
# Figure 4: Employment, Health, and Living Arrangements over the Life Course: Aggregate
fac_row_agg_count_out(
  outcomes_weighted_country,
  measures,
  measures_labs_agg,
  theme_top_count())+ 
  labs(y = "Proportion", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+
  scale_y_continuous(breaks=c(0,0.5, 1), labels = c('0', '-', '1'))

```



```{r outcomes_gender_weighted, fig.cap="Employment. Age Group and Gender. Countries. Weighted.", echo=FALSE, fig.height=70, fig.width=45, dev = c("png"), dpi=100}
# Figure 5: Employment, Health, and Living Arrangements over the Life Course: Country Level
graph_agg_data_main(weighted=TRUE)

```


```{r disabilities_aggregate_weighted, echo=FALSE,  fig.height=12, fig.width=19, dev = c("png"), dpi=100}
# Figure 6: Functional Limitations over the Life Course
fac_row_agg_count_dis(
  outcomes_weighted_country_lim,
  limitations,
  limitations_labs,
  theme_top_count(
    size_text=23,
    size_title=28,
    size_legend=18,
    color="#344771"
  ))+ 
  labs(y = "Proportion", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+ 
  scale_y_continuous(breaks=c(0,0.5, 1), labels = c('0', '-', '1'), limits = c(0, 1))


```


```{r disabilities_gender_weighted, fig.cap="Functional Limitations by Age Group and Gender. Weighted", echo=FALSE, fig.height=35, fig.width=45, dev = c("png"), dpi=100}
# Figure 7: Health and Health Care

b <- fac_row__("diff_seei", theme_top_a()) + 
  ylim(0, 1) + 
  labs(y = "          Seeing          ", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )   + theme(legend.position = "none") + scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))

c <- fac_row("diff_hear", theme_middle()) + 
  ylim(0, 1) + 
  labs(y = "  Hearing") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="top"
      )+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
d <- fac_row("diff_reme", theme_bottom()) +
  ylim(0, 1) + labs(y = "        Remembering", x = "")+ scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+  theme(legend.position = "none")+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
e <- fac_row("diff_walk_clim", theme_middle()) + ylim(0, 1) + labs(y = "   Walking or \n Climbing")+ scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="top"
      )+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
f <- fac_row("diff_self_care", theme_middle()) + ylim(0, 1) + labs(y = " Self Care", x = "Age")+ scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+  theme(legend.position = "none")+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))

i <- fac_row("diff_comm", theme_bottom()) + ylim(0, 1) + labs(y = "        Communicating", x = "\n\n\nAge")+ scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
plot_grid(b, c, d, e, f, i, ncol=1, align='v', rel_heights = c(7.7, 5, 5.8, 5, 5, 9.8), labels =c("A.-", "B.-", "C.-","D.-", "E.-", "F.-"), label_size = 38,label_colour = "#14213D")

```

\end{landscape}


# Appendix

\begin{landscape}


```{r ov65_dep_rat, echo=FALSE, fig.height=7.5, fig.width=18, dev = c("png"), dpi=100}

# Appendix: Figure 1
wrap_elements(panel = depratov65  + oldageratov65) +
  labs(tag = "**Year**") +
  theme(
    plot.tag = element_markdown(size=20, color="#344771"),
    plot.tag.position = "bottom"
  )
```


```{r outcomes_aggregate_nonweighted, fig.cap="Employment. Age Group and Gender.", echo=FALSE,  fig.height=25, fig.width=25, dev = c("png"), dpi=100}
# Appendix: Figure 3 - Employment, Health, and Living Arrangements over the Life Course: Aggregate
fac_row_agg_count_out(
  outcomes_nonweighted_country,
  measures,
  measures_labs_agg,
  theme_top_count())+ 
  labs(y = "Proportion", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+
  scale_y_continuous(breaks=c(0,0.5, 1), labels = c('0', '-', '1'))

```



```{r outcomes_gender_nonweighted, fig.cap="Outcomes by Age Group and Gender. Not Weighted", echo=FALSE, fig.height=60, fig.width=45, dev = c("png"), dpi=100}
# Appendix: Figure 4 - Employment, Health, & Living Arrangements over the Life Course: Country-level, no weights
graph_agg_data_main(weighted=FALSE)

```



```{r disabilities_aggregate_nonweighted, echo=FALSE,  fig.height=12, fig.width=19, dev = c("png"), dpi=100}
# Appendix: Figure 5 - Functional Limitations over the Life Course: Aggregate, no weights
fac_row_agg_count_dis(
  outcomes_nonweighted_country_lim,
  limitations,
  limitations_labs,
  theme_top_count(
    size_text=23,
    size_title=28,
    size_legend=18,
    color="#344771"
  ))+ 
  labs(y = "Proportion", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+ 
  scale_y_continuous(breaks=c(0,0.5, 1), labels = c('0', '-', '1'), limits = c(0, 1))

```


```{r disabilities_gender_nonweighted, fig.cap="Functional Limitations by Age Group and Gender. Weighted", echo=FALSE, fig.height=35, fig.width=45, dev = c("png"), dpi=100}
# Appendix: Figure 6 - Functional Limitations over the Life Course: Country-level, no weights
b <- fac_row__("diff_seei", theme_top_a(), weighted=FALSE) + 
  ylim(0, 1) + 
  labs(y = "          Seeing          ", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )   + theme(legend.position = "none") + scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))

c <- fac_row("diff_hear", theme_middle(), weighted=FALSE) + 
  ylim(0, 1) + 
  labs(y = "  Hearing") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="top"
      )+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
d <- fac_row("diff_reme", theme_bottom(), weighted=FALSE) +
  ylim(0, 1) + labs(y = "        Remembering", x = "")+ scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+  theme(legend.position = "none")+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
e <- fac_row("diff_walk_clim", theme_middle(), weighted=FALSE) + ylim(0, 1) + labs(y = "   Walking or \n Climbing")+ scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="top"
      )+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
f <- fac_row("diff_self_care", theme_middle(), weighted=FALSE) + ylim(0, 1) + labs(y = " Self Care", x = "Age")+ scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+  theme(legend.position = "none")+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))

i <- fac_row("diff_comm", theme_bottom(), weighted=FALSE) + ylim(0, 1) + labs(y = "        Communicating", x = "\n\n\nAge")+ scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
plot_grid(b, c, d, e, f, i, ncol=1, align='v', rel_heights = c(7.7, 5, 5.8, 5, 5, 9.8), labels =c("A.-", "B.-", "C.-","D.-", "E.-", "F.-"), label_size = 38,label_colour = "#14213D")


```

\end{landscape}

