---
title: "Demography of Aging in South Saharan Africa"
output: 
  bookdown::pdf_document2:
    toc: false
    extra_dependencies: ["flafter"]
    number_sections: true
    df_print: kable
    highlight: tango
    keep_tex: true
    fig_caption: yes
fontsize: 11pt
geometry: margin=1in
header-includes:
  \usepackage{pdflscape}
  \usepackage{lscape}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.align = "center",
	fig.height = 4.5,
	fig.width = 5,
	message = FALSE,
	warning = FALSE,
  graphics.auto_pdf = FALSE
	)
```

```{r env, include=FALSE}
# Load & Install Packages
pacman::p_load(
  ggtext,
  tidyr, 
  haven, 
  plyr, 
  dplyr, 
  magrittr,
  ggplot2, 
  CGPfunctions, 
  scales, 
  ggh4x, 
  cowplot, 
  stats,
  stringr,
  reshape2,
  directlabels,
  ggstream,
  patchwork,
  ggrepel,
  forcats,
  ggh4x

)
source("../src/utils/constants.R")
source("../src/utils/funcs.R")
```

```{r data_load, include=FALSE}
data_list <- lapply(files_to_load, load_data)
names(data_list) <- gsub("\\.dta$", "", names_datas)
list2env(data_list, envir = .GlobalEnv)
```

```{r data_trans, include=FALSE}
# Main pipeline

subsaharan_weighted <- rbind(
  subsaharan_weighted %>% mutate(country = 'ssa'),
  countries_weighted
)
subsaharan_nonweighted <- rbind(
  subsaharan_nonweighted %>% mutate(country = 'ssa'),
  countries_nonweighted
)


proj_pop <- projections %>%
  select(country, pop_60plus_1990, pop_60plus_2020, pop_60plus_2050) %>%
  rename(
    `1990` = pop_60plus_1990,
    `2020` = pop_60plus_2020,
    `2050` = pop_60plus_2050
  ) %>%
  mutate(across(starts_with("19"), round, 0)) %>%
  gather(measurement, value, `1990`:`2050`, factor_key = TRUE) %>%
  filter(country %in% countries) %>%
  mutate(value = round(value, 1)) %>%
  mutate(
    measurement = factor(measurement, levels = breaks_text[-length(breaks_text)], ordered = TRUE)
  )

totpop <- pop_pro %>%
  select(
    countryregion, 
    pop_total_1990, 
    pop_total_2020, 
    pop_total_2050, 
    pop_total_2100
    ) %>%
  filter(countryregion %in% keepobs) %>%
  add_rest_of_world("pop_total") %>%
  reshape_and_clean("pop_total", keepobs, order) 

totpop$name_lab <- name_lab
totpop$measurement_x <- measurement_x
totpop$lab <- lab

over60 <- pop_pro %>%
  select(countryregion, pop_60plus_1990, pop_60plus_2020, pop_60plus_2050, pop_60plus_2100) %>%
  filter(countryregion %in% keepobs) %>%
  add_rest_of_world("pop_60plus") %>%
  reshape_and_clean("pop_60plus", keepobs, order)

# Additional adjustments for over60 labels
over60$name_lab <- c(
  NA, NA, NA, NA, '+ 171 %', '+ 155 %', '+ 121 %', NA, 
  '+ 100 %', '+ 144 %', '+ 194 %', NA,
  '- 29 %', '+ 59 %', '+ 313 %', NA
)
over60$lab <- c(
  '94 M ', '57 M ', '24 M', NA, NA, NA, NA, NA, 
  NA, NA, NA, NA,
  '362 M', '552 M', '644 M', NA
)

dep_rat_ov60 <- process_dependency_ratio(pop_pro, "depratio_15to59_", coun_comp)
old_age_rat_ov60 <- process_dependency_ratio(pop_pro, "oldagedepratio_15to59_", coun_comp)
dep_rat_ov65 <- process_dependency_ratio(pop_pro, "depratio_15to64_", coun_comp)
old_age_rat_ov65 <- process_dependency_ratio(pop_pro, "oldagedepratio_15to64_", coun_comp)

# Final adjustments for old_age_rat_ov60 and old_age_rat_ov65 labels
old_age_rat_ov60 <- old_age_rat_ov60 %>%
  mutate(name_lab = if_else(name_lab == 'Sub-Saharan Africa', 'Sub-Saharan Africa\n             Avg.', name_lab))

old_age_rat_ov65 <- old_age_rat_ov65 %>%
  mutate(name_lab = if_else(name_lab == 'Sub-Saharan Africa', 'Sub-Saharan Africa\n             Avg.', name_lab))


ssa <- ssa %>%
  mutate(
    gen = female,
    female = as.factor(female),
    age_group5 = as.factor(age_group5)
  ) %>%
  recode_values("female", c(`0` = 'Male', `1` = 'Female')) %>%
  recode_values("country", country_mapping) %>%
  mutate(
    region = ifelse(country %in% names(region_mapping), region_mapping[country], 'Other'),
    work_hrs = case_when(
      work_hrs >= 140 & work_hrs <= 168 ~ 140,
      work_hrs > 168 ~ NA_real_,
      TRUE ~ work_hrs
    ),
    depressed = ifelse(country == 'Nigeria', NA, depressed),
    gender = as.factor(female)
  )

stacked_labels <- data.frame(
  labels = rev(order),
  countryregion = rev(order),
  condition = c(2060, 2069, 2070, 2055),
  measurement = c(2670000, 5300000, 6600000, 8600000),
  color = c("black", "white", "white", "black")
)

dat <- dat %>%
  select(head(var_sum, -1)) %>%
  arrange(desc(govtexpgdp)) %>%
  mutate(cou = ifelse(country %in% countries, 1, 0),
         oopexp = 100 - oopexp)

dat_long <- prep_data_long(
  dat %>% filter(cou != 0),
  countries
)


# Apply the function for each income group
high_inco <- process_income_group(dat, 'HIC')
low_middle_inco <- process_income_group(dat, 'LMICs_nonSSA')
sub_sahar_inco <- process_income_group(dat, 'Sub-Saharan Africa')

```

```{r functions, include=FALSE}

trans_input_count_gender <- function(
    data,
    var_vec,
    ids = c("female", "age_group5"),
    var_nam="condition",
    val_nam="measurement"
 
){
  data$age_group5 <- as.factor(data$age_group5)
  data$work_hrs = data$work_hrs/40
  data = melt(data,
      id.vars=ids,
      measure.vars=var_vec,
      variable.name=var_nam,
      value.name=val_nam
  )
  
  data <- data %>% 
    group_by(female, age_group5, condition) %>%  # Group by gender and age group only
    filter(!age_group5  %in% c('0', '5', '10', '15')) %>% 
        summarize(
      !!val_nam := mean(get(val_nam), na.rm = TRUE),  # Example: take mean of the measurement
      .groups = 'drop'  # Drop the group structure after summarizing
    ) %>%
    ungroup() 
  return (data)
}

trans_input_count <- function(
    data,
    var_vec,
    ids = c("country", "age_group5"),
    var_nam="condition",
    val_nam="measurement"
 
){
  data$age_group5 <- as.factor(data$age_group5)
  data$work_hrs = data$work_hrs/40
  data = melt(data,
      id.vars=ids,
      measure.vars=var_vec,
      variable.name=var_nam,
      value.name=val_nam
  )
  
  data <- data %>% 
    group_by(age_group5, country) %>% 
    filter(!age_group5  %in% c('0', '5', '10', '15')) %>% 
    mutate(
      country = case_when(
        country == 'eth'
         ~ 'Ethiopia',
        country == 'mlw'
         ~ 'Malawi',  
        country == 'nga'
         ~ 'Nigeria',  
        country == 'tza'
         ~ 'Tanzania',  
        country == 'gha'
         ~ 'Ghana', 
        country == 'saf'
         ~ 'South~Africa',
        country == 'uga'
         ~ 'Uganda',
        country == 'niger'
         ~ 'Niger',
        country == 'ssa'
         ~ 'Average',
        TRUE ~ NA)
    )
  return (data)
}

#' Theme for general outcomes in selected countries in Africa, which include
#' remaining life expectancy, social protection, pension coverage, health care
#' out of poclet, gov health, n of hospital beds, n of physicians
theme_broad_outc <- function(
    size_text=18,
    size_title=23,
    size_legend=20,
    color="#344771"
){
  top = theme(
    axis.title.x = element_blank(),
    panel.background = element_blank(),
    plot.background = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    strip.background=element_rect(fill = "transparent", color = NA),
    axis.text = element_text(color = color, size = size_text, hjust = 0),
    axis.text.y = element_blank(),
    legend.background = element_blank(),
    legend.box.background = element_blank(),
    legend.position="bottom", 
    axis.line.x.bottom =element_line(),
    axis.line.x.top =element_line(),
    legend.text = element_text(
      margin = margin(t = size_legend, b = size_text, unit = "pt"),
      size=size_legend
      ),
    legend.key.size = unit(3.5,"line"), 
    legend.key = element_blank(),
    text = element_text(size = size_text, color=color), 
    strip.text = element_markdown(color = color, size=size_title),
    axis.title.y = element_text(angle = 0),
    panel.spacing = unit(1.5, "lines"),
    plot.margin = margin(, 1.2, , , "cm")

    )
}


theme_top_count <- function(
    size_text=35,
    size_title=42,
    size_legend=32,
    color="#344771"
){
  top = theme(
    legend.position="bottom", 
    legend.justification="right",
    legend.title=element_blank(),
    legend.text=element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend
      ),
    legend.key.size = unit(6,"line"), 
    strip.background=element_rect(fill = "transparent", color = NA),
    axis.text = element_markdown(color = color, size = size_text),
    text = element_text(size = size_text), 
    strip.text = element_markdown(color = color, size=size_text),
    panel.grid.major = element_line(linetype="dashed"),

    axis.title = element_text(margin = margin(l = 20, b=20), color=color, size=size_text, face='bold'),
    panel.spacing.x = unit(5, "lines"),
    panel.spacing.y = unit(3, "lines")
    )

  return (top)
} 
theme_top_a <- function(
    size_text=35,
    size_title=42,
    size_legend=42,
    color="#344771"
){
  top = theme(
    axis.title.x = element_blank(),
    strip.background=element_rect(fill = "transparent", color = NA),
    panel.grid.major = element_line(linetype="dashed"),
    axis.text = element_text(color = color, size = size_title, hjust = 0),


    axis.text.x = element_blank(),
    legend.position="top", 
    legend.justification = "right",
    axis.ticks.x = element_blank(),
    legend.title=element_blank(),
    legend.text = element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend,
      color = color
      ),
    legend.key.size = unit(6,"line"), 

    text = element_text(size = size_text, color=color), 
    strip.text = element_text(color = color, face = "bold", size=size_title),
    axis.title.y = element_text(angle = 0, size=size_title),
    panel.spacing.x = unit(5, "lines"),
    panel.spacing.y = unit(7, "lines"),
    plot.margin = margin(, 2, , , "cm")

    )

  return (top)
}

theme_top <- function(
    size_text=35,
    size_title=42,
    size_legend=42,
    color="#344771"

){
  top = theme(
    axis.title.x = element_blank(),
    strip.background=element_rect(fill = "transparent", color = NA),
    panel.grid.major = element_line(linetype="dashed"),
    axis.text = element_text(color = color, size = size_title, hjust = 0),


    #axis.text.x = element_blank(),
    legend.position = "none", 
    legend.justification = "right",
    axis.ticks.x = element_blank(),
    legend.title=element_blank(),
    legend.text = element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend,
      color = color
      ),
    legend.key.size = unit(6,"line"), 

    text = element_text(size = size_text, color=color), 
    strip.text = element_text(size = size_text, color=color, face = "bold"),
    axis.title.y = element_markdown(angle = 0, size=size_title),
    panel.spacing.x = unit(5, "lines"),
    panel.spacing.y = unit(7, "lines"),
    plot.margin = margin(, 2, , , "cm")

    )

  return (top)
}


theme_middle <- function(
    size_text=35,
    size_title=42,
    color="#344771"

){
  middle = theme(
    strip.background = element_blank(),
    axis.text.y = element_text(color = color, size = size_title, hjust = 0),
    plot.background=element_rect(fill = "transparent", color = NA),
        panel.grid.major = element_line(linetype="dashed"),

    strip.text.x = element_blank(), 
    
    text = element_text(size = size_text, color=color), 
    legend.position="none",
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_text(angle = 0, size=size_title),
    panel.spacing.x = unit(5, "lines"),
    panel.spacing.y = unit(7, "lines"),
    plot.margin = margin(, 2, , , "cm")
    )

  return (middle)
}


theme_bottom <- function(
    size_text=38,
    size_title=42,
    size_legend=32,
    color="#344771"
){
  bottom = theme(
    strip.background = element_blank(),
    plot.background=element_rect(fill = "transparent", color = NA),
    axis.text = element_text(color = color, size = size_title, hjust = 0),
    strip.text.x = element_blank(), 
    legend.position="bottom", 
    legend.justification = "right",
    legend.title=element_blank(),
        panel.grid.major = element_line(linetype="dashed"),

    legend.text = element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend,
      color = color
      ),
    legend.key.size = unit(6,"line"), 
    
    text = element_text(size = size_text, color=color),
    axis.title.y = element_text(angle = 0, size=size_title),
    axis.title.x = element_text(size=size_title, color=color, face = "bold"),
    panel.spacing.x = unit(5, "lines"),
    panel.spacing.y = unit(7, "lines"),
    plot.margin = margin(, 2, , , "cm")
    )

  return (bottom)
}

get_count <- function(
    var
){
  ssa0 <- ssa
  ssa0
  ssa0$country = ''
  ssa0$region = "Average"
  ssa <- bind_rows(ssa0, ssa)
  annot0 = ssa %>% 
  filter(
    age==20 & gender=='Male'
    ) %>% 
  group_by(age_group5, country, gender, region) %>% 
    summarise(vari = mean(get(var), na.rm = TRUE), .groups = 'drop')
  
  
  # Calculate count for age >= 20 and non-NA gender
  annot1 = ssa %>% 
    filter(age >= 20 & !is.na(gender)) %>% 
    group_by(country, gender) %>% 
    summarise(n = sum(!is.na(country) & !is.na(get(var))), .groups = 'drop') %>%
    group_by(country) %>% 
    summarise(n = paste0("N=", scales::comma(sum(n), accuracy = 1)), .groups = 'drop')
  
  # Merge the two summaries
  count <- merge(annot0, annot1, by = "country")
  
  return(count)
}

fac_row_popu <- function(
    forma_theme,
    colors = c("Female" = "#8eb67d", "Male" = "#000C66"),
    breaks=c("20","25","30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80"),
    labels=c("20", "", "", "", "40", "", "",  "", "60", "", "", "", "80+"),
    size_count=12

){
  
  dat = get_count("gender")
  subsah <- ssa
  subsah$country <- ''
  subsah$region <-  "Average"
  ssa <- bind_rows(ssa, subsah)
  ssa = ssa %>% filter(!age_group5  %in% c('0', '5', '10', '15'))
  ssa$gender <- factor(ssa$gender, levels = c("Female", "Male"))
  graph <- ssa %>%
    filter(age>=20  & !is.na(gender))%>%  ggplot(
      aes(x = age_group5, fill=gender)
      ) + 
    theme_minimal() +
    geom_bar(binwidth = 0.5, color = "white", position = "dodge") +
    facet_nested(~factor(region, levels=regions) +country, scales='free_y', space="free_y", nest_line = element_line(linetype = 1)) +
 force_panelsizes(cols = c(1, rep(0.85, 7))) +
    scale_fill_manual("legend", values = colors)+
    geom_text(
      data = dat, 
      label = dat$n,
      aes(label = paste0("N=", n), y = Inf, x  = -Inf),
      vjust = 1,
      colour="#14213D",
      hjust = -0.2,
      size = size_count
      ) + forma_theme

  return (graph)
}


fac_row__<- function(
    var,
    forma_theme,
    weighted=TRUE,
    colors=c("#8eb67d","#000C66"),
    size_count=12
){
  
  dat = get_count(var)
  
  if (weighted) {
    data <- ssa %>% 
      filter(
        age>=20 & !is.na(gender) 
        ) %>% 
      group_by(age_group5, country, gender, region) %>% 
      summarise(vari = weighted.mean(get(var), weights_survey, na.rm=TRUE)) 
    data$age_group5 <- as.factor(data$age_group5)

    ssa_agg = ssa_agg %>% mutate(vari = get(var))
    ssa_agg = ssa_agg %>% 
        mutate(
          female = case_when(
          female==0
           ~ 'Male',
          female ==1
          ~ 'Female',
          TRUE ~ NA),
          work_hrs = case_when(
            work_hrs>=140 & work_hrs<=168 ~ 140,
            work_hrs>168 ~ NA,
            TRUE ~ work_hrs
            )
          )
    ssa_agg$gender <- as.factor(ssa_agg$female)
    ssa_agg <- ssa_agg %>% 
      filter(
        !is.na(gender) 
        ) 
    ssa_agg$age_group5 <- as.factor(ssa_agg$age_group5)
    ssa_agg = ssa_agg %>% filter(!age_group5  %in% c('0', '5', '10', '15'))

    ssa_agg$country = ''
    #ssa_agg$region =  "**Average**"
    ssa_agg$region =  "Average"

    data=bind_rows(data,ssa_agg)
    
  } else {
    data <- ssa %>% 
      filter(
        age>=20 & !is.na(gender) 
        ) %>% 
      group_by(age_group5, country, gender, region) %>% 
      summarise(vari = mean(get(var), na.rm=TRUE))
    data$age_group5 <- as.factor(data$age_group5)

    ssa_agg_non$gender <- as.factor(ssa_agg_non$female)
    ssa_agg_non <- ssa_agg_non %>% 
      filter(
        !is.na(gender) 
        ) 
    ssa_agg_non = ssa_agg_non %>% mutate(vari = get(var))
    ssa_agg_non = ssa_agg_non %>% 
        mutate(
          female = case_when(
          female==0
           ~ 'Male',
          female ==1
          ~ 'Female',
          TRUE ~ NA),
          work_hrs = case_when(
            work_hrs>=140 & work_hrs<=168 ~ 140,
            work_hrs>168 ~ NA,
            TRUE ~ work_hrs
            )
          )
    ssa_agg_non$gender <- as.factor(ssa_agg_non$female)
    ssa_agg_non <- ssa_agg_non %>% 
      filter(
        !is.na(gender) 
        ) 
    ssa_agg_non$age_group5 <- as.factor(ssa_agg_non$age_group5)
    
    ssa_agg_non$country = ''
    #ssa_agg_non$region =  "**Average**"
    ssa_agg_non$region =  "Average"

    ssa_agg_non = ssa_agg_non %>% filter(!age_group5  %in% c('0', '5', '10', '15'))

    data=bind_rows(data,ssa_agg_non)
  
  }
  
  graph = ggplot(
      data,
      aes(x = age_group5, y = vari, colour = gender, group=gender)
      ) + 
    theme_minimal() +
    geom_line(size = 3, aes(linetype=gender)) +
        facet_nested(~factor(region, levels=regions) +country, scales='free_y', space="free_y", nest_line = element_line(linetype = 1)) +     force_panelsizes(cols = c(1, rep(0.85, 7))) +

   scale_color_manual(values = colors) +
    
    scale_linetype_manual(values=c("solid", "longdash"))  +
    geom_text(
      data = dat, 
      label=dat$n,
      aes(label = paste0("N=", n), y = Inf, x  = -Inf),
      vjust = 1,
      colour="#14213D",
      hjust = -0.2,
      size = size_count
      ) +
      geom_rect(
        aes(xmin = "60", xmax = Inf, ymin = -Inf, ymax = Inf),
        alpha = 0.005,
        fill = "#8eb67d"
          ) +
    forma_theme

  return (graph)
}

fac_row <- function(
    var,
    forma_theme,
    weighted=TRUE,
    colors=c("Female" = "#8eb67d", "Male" = "#000C66"),
    size_count=12
){
  
  dat = get_count(var)
  
  if (weighted) {
    data <- ssa %>% 
      filter(
        age>=20 & !is.na(gender) 
        ) %>% 
      group_by(age_group5, country, gender, region) %>% 
  summarise(vari = weighted.mean(get(var), weights_survey, na.rm = TRUE), .groups = "drop")
    data$age_group5 <- as.factor(data$age_group5)

    ssa_agg = ssa_agg %>% mutate(vari = get(var))
    ssa_agg = ssa_agg %>% 
        mutate(
          female = case_when(
          female==0
           ~ 'Male',
          female ==1
          ~ 'Female',
          TRUE ~ NA),
          work_hrs = case_when(
            work_hrs>=140 & work_hrs<=168 ~ 140,
            work_hrs>168 ~ NA,
            TRUE ~ work_hrs
            )
          )
    ssa_agg$gender <- as.factor(ssa_agg$female)
    ssa_agg <- ssa_agg %>% 
      filter(
        !is.na(gender) 
        ) 
    ssa_agg$age_group5 <- as.factor(ssa_agg$age_group5)
    ssa_agg = ssa_agg %>% filter(!age_group5  %in% c('0', '5', '10', '15'))

    ssa_agg$country = ''
    ssa_agg$region =  "Average"
    
    data=bind_rows(data,ssa_agg)
    
  } else {
    data <- ssa %>% 
      filter(
        age>=20 & !is.na(gender) 
        ) %>% 
      group_by(age_group5, country, gender, region) %>% 
  summarise(vari = weighted.mean(get(var), weights_survey, na.rm = TRUE), .groups = "drop")
    data$age_group5 <- as.factor(data$age_group5)

    ssa_agg_non$gender <- as.factor(ssa_agg_non$female)
    ssa_agg_non <- ssa_agg_non %>% 
      filter(
        !is.na(gender) 
        ) 
    ssa_agg_non = ssa_agg_non %>% mutate(vari = get(var))
    ssa_agg_non = ssa_agg_non %>% 
        mutate(
          female = case_when(
          female==0
           ~ 'Male',
          female ==1
          ~ 'Female',
          TRUE ~ NA),
          work_hrs = case_when(
            work_hrs>=140 & work_hrs<=168 ~ 140,
            work_hrs>168 ~ NA,
            TRUE ~ work_hrs
            )
          )
    ssa_agg_non$gender <- as.factor(ssa_agg_non$female)
    ssa_agg_non <- ssa_agg_non %>% 
      filter(
        !is.na(gender) 
        ) 
    ssa_agg_non$age_group5 <- as.factor(ssa_agg_non$age_group5)
    
    ssa_agg_non$country = ''
    ssa_agg_non$region =  "Average"
    ssa_agg_non = ssa_agg_non %>% filter(!age_group5  %in% c('0', '5', '10', '15'))

    data=bind_rows(data,ssa_agg_non)
  
  }
    data$gender <- factor(data$gender, levels = c("Female", "Male"))

    graph = ggplot(
      data,
      aes(x = age_group5, y = vari, colour = gender, group=gender)
      ) + 
    theme_minimal() +
    geom_line(size = 3, aes(linetype=gender)) +
    facet_nested(~factor(region, levels=regions) +country, scales='free_y', space="free_y")+    scale_color_manual(values = colors) +
     force_panelsizes(cols = c(1, rep(0.85, 7))) +

    scale_linetype_manual(values=c("Female" = "solid", "Male" = "longdash"))  +
    geom_text(
      data = dat, 
      label=dat$n,
      aes(label = paste0("N=", n), y = Inf, x  = -Inf),
      vjust = 1,
      colour="#14213D",
      hjust = -0.2,
      size = size_count
      ) +
      geom_rect(
        aes(xmin = "60", xmax = Inf, ymin = -Inf, ymax = Inf),
        alpha = 0.005,
        fill = "#8eb67d"
          ) + forma_theme +
  guides(
        linetype = "none",  # Hide the linetype legend

    colour = guide_legend(title = "Gender", 
                          override.aes = list(linetype = c("Female" = "solid", "Male" = "longdash")))  # Combine color and linetype in one legend
  )

  return (graph)
}



fac_row_agg_count_out <- function(
    data,
    vars,
    labels,
    forma_theme,
    size_count=10
){
  
  condition.labs <- labels
  names(condition.labs) <- vars
  levels(data$age_group5) <- c(levels(data$age_group5),'')
  levels(data$age_group5) <- c(levels(data$age_group5),'')
  f_labels <- data.frame(
    condition = measures[-length(measures)], 
    country = c( "Average", "", "", "", "", "", "", "", ""),
    label = c( "Average", "", "", "", "", "", "", "", "Average"))
  f_labels$condition = factor(f_labels$condition)

  graph <-data %>%  
    filter(condition!='healthinsurance_ever') %>% 
    mutate(label = ifelse(country== "Average", country, NA)) %>%
    ggplot(
      aes(x = age_group5, y = measurement, colour = I(ifelse(country ==  "Average", "#050A30", "#D3D3D3")), group=country)
      ) +
    facet_wrap(
      . ~condition, 
      ncol = 3, 
      labeller = labeller(condition=condition.labs)#,
      #scales='free_y'

      ) +
    geom_rect(
      aes(xmin = "60", xmax = "80", ymin = -Inf, ymax = Inf),
      #alpha = 0.009,
      alpha=0.006,
      fill="#344771"
      #fill = "#000C66"
        ) +
    #geom_dl(aes(label = label), method = list(dl.trans(x = x + 0.05), "last.points", cex = 0.8)) +
    theme_minimal() +
    #geom_line(size = 1) +
    geom_line(size=1.1) +
    geom_line(data = filter(data, (country ==  "Average" & condition!='healthinsurance_ever')), size = 2, linetype="solid")+#, linetype="dashed")+
  geom_text(x = "40", y = 0.25, aes(label = label), data = f_labels, size=9, color="#050A30")+

    scale_fill_manual(values = c("#D3D3D3")) +
    forma_theme
  
  
  return (graph)
}

 
fac_row_agg_count_dis <- function(
    data,
    vars,
    labels,
    forma_theme,
    size_count=10
){
  condition.labs <- labels
  names(condition.labs) <- vars
  levels(data$age_group5) <- c(levels(data$age_group5),'')
  levels(data$age_group5) <- c(levels(data$age_group5),'')
  f_labels <- data.frame(condition = c("diff_seei", 
  "diff_hear",
  "diff_reme",
  "diff_walk_clim",
  "diff_self_care",
  "diff_comm"), country = c( "Average", "", "", "", "", ""),
  label = c( "Average", "", "", "", "",  "Average"))
  f_labels$condition = factor(f_labels$condition)

  graph <-data %>%  
    filter(str_detect(condition, 'diff')) %>% 
    mutate(label = ifelse(country==  "Average", country, NA)) %>%
    ggplot(
      aes(x = age_group5, y = measurement, colour = I(ifelse(country ==  "Average", "#050A30", "#D3D3D3")), group=country)
      ) + 
    facet_wrap(
      . ~condition, 
      ncol = 3, 
      labeller = labeller(condition=condition.labs)#,
      #scales='free_y'

      ) +
    geom_rect(
      aes(xmin = "60", xmax = "80", ymin = -Inf, ymax = Inf),
      alpha=0.006,
      fill="#344771"
        ) +
    theme_minimal() +
    geom_line(size=1.1) +
    geom_line(data = filter(data, (country ==  "Average" & str_detect(condition, 'diff'))), size = 2, linetype="solid")+
  geom_text(x = "40", y = 0.15, aes(label = label), data = f_labels, size=9, color="#050A30")+

    scale_fill_manual(values = c("#D3D3D3")) +

    forma_theme
  
  
  return (graph)
}

graph_agg_data_main <- function(weighted = TRUE, breaks = bre_age, labels = lab_age) {
  
  a <- fac_row_popu(theme_top()) + 
    labs(y = "**Observations<br>(Count)**", face = 'bold') +
    scale_x_discrete(
      breaks = breaks,
      labels = labels,
      position = "bottom"
    ) + 
    scale_y_continuous(
      breaks = c(0, 20000, 40000), 
      limits = c(0, 50000), 
      labels = c('0', '20K', '40K')
    )
  
  b <- fac_row("disability", theme_middle(), weighted) + 
    labs(y = "           Functional     \n           Limitations     \n           (Proportion)     ", x = "Age") +
    scale_x_discrete(
      breaks = breaks,
      labels = labels,
      position = "top"
    ) + 
    scale_y_continuous(
      breaks = c(0, 0.5, 1), 
      limits = c(0, 1.2), 
      labels = c('0', '-', '1')
    ) +
    theme(legend.position = "none")
  
  c <- fac_row("ill_inj", theme_middle(), weighted) + 
    labs(y = "Illness & Injury\n(Proportion)") + 
    scale_x_discrete(
      breaks = breaks,
      labels = labels,
      position = "top"
    ) + 
    scale_y_continuous(
      breaks = c(0, 0.5, 1), 
      limits = c(0, 1.2), 
      labels = c('0', '-', '1')
    )
  
  d <- fac_row("ill_inj_stopactivity", theme_middle(), weighted) + 
    labs(y = "     Stopped Activities\n(Proportion)") +
    scale_x_discrete(
      breaks = breaks,
      labels = labels,
      position = "top"
    ) + 
    scale_y_continuous(
      breaks = c(0, 0.5, 1), 
      limits = c(0, 1.2), 
      labels = c('0', '-', '1')
    )
  
  e <- fac_row("depressed", theme_middle(), weighted) + 
    labs(y = "  Depression\n  Or Psych Distress\n  (Proportion)", x = "Age") + 
    scale_x_discrete(
      breaks = breaks,
      labels = labels,
      position = "top"
    ) + 
    scale_y_continuous(
      breaks = c(0, 0.5, 1), 
      limits = c(0, 1.2), 
      labels = c('0', '-', '1')
    )
  
  f <- fac_row("work_any", theme_middle(), weighted) + 
    labs(y = "Employment\nStatus\n(Proportion)") + 
    scale_x_discrete(
      breaks = breaks,
      labels = labels,
      position = "top"
    ) + 
    scale_y_continuous(
      breaks = c(0, 0.5, 1), 
      limits = c(0, 1.2), 
      labels = c('0', '-', '1')
    )
  
  g <- fac_row("work_hrs", theme_middle(), weighted) + 
    labs(y = "Weekly\nEmployment Status\n(Hours)", x = "Age") + 
    scale_x_discrete(
      breaks = breaks,
      labels = labels,
      position = "top"
    ) + 
    scale_y_continuous(
      breaks = c(0, 20, 40), 
      limits = c(0, 50), 
      labels = c('0', '-', '40')
    )
  
  h <- fac_row("notmarried", theme_middle()) + 
    labs(y = "Unmarried\n(Proportion)") + 
    scale_x_discrete(
      breaks = breaks,
      labels = labels,
      position = "top"
    ) + 
    scale_y_continuous(
      breaks = c(0, 0.5, 1), 
      limits = c(0, 1.2), 
      labels = c('0', '-', '1')
    )
  
  i <- fac_row("lives_alone", theme_middle(), weighted) + 
    labs(y = "Living alone\n(Proportion)", x = "Age") + 
    scale_x_discrete(
      breaks = breaks,
      labels = labels,
      position = "top"
    ) + 
    scale_y_continuous(
      breaks = c(0, 0.5, 1), 
      limits = c(0, 1.2), 
      labels = c('0', '-', '1')
    )
  
  j <- fac_row("urban", theme_bottom(), weighted) + 
    labs(y = " Urban Status\n(Proportion)", x = "\n \n\nAge", color = "#344771") + 
    scale_x_discrete(
      breaks = breaks,
      labels = labels,
      position = "bottom"
    ) + 
    scale_y_continuous(
      breaks = c(0, 0.5, 1), 
      limits = c(0, 1.2), 
      labels = c('0', '-', '1')
    ) +
  geom_line(aes(color = gender), size = 1) 
  plot_grid(
    a, b, c, d, e, f, g, h, i, j,  
    rel_heights = c(9, 5,  5, 5, 5, 5, 5, 5, 5, 7.5),
    ncol = 1, 
    nrow = 10, 
    align = "v", 
    labels = c("*", "A.-", "B.-", "C.-","D.-", "E.-", "F.-", "G.-", "H.-", "I.-"),
    label_size = 38,
    label_colour = "#14213D"
  )
}

fac_row_agg_gen_dis <- function(
  data,
  vars,
  labels,
  forma_theme,
  size_count = 10
){
  
  condition.labs <- labels
  names(condition.labs) <- vars
  condition_order <- c(
    "diff_seei", 
    "diff_hear", 
    "diff_reme", 
    "diff_walk_clim", 
    "diff_self_care", 
    "diff_comm"
  )
  
  data$condition <- factor(data$condition, levels = condition_order)

  levels(data$age_group5) <- c(levels(data$age_group5), '')
  f_labels <- data.frame(
    condition = condition_order,  
    female = c("Male", "", "", "", "", ""),
    label = c("Male", "", "", "", "", "")
  )
  f_labels$condition = factor(f_labels$condition, levels = condition_order)

  f_labels2 <- data.frame(
    condition = condition_order,  
    female = c("Female", "", "", "", "", ""),
    label = c("Female", "", "", "", "", "")
  )
  f_labels2$condition = factor(f_labels2$condition, levels = condition_order)

  data$female <- factor(data$female, levels = c(1, 0), labels = c("Female", "Male"))

  graph <- data %>%  
    filter(str_detect(condition, 'diff')) %>% 
    ggplot(
      aes(x = age_group5, y = measurement, group = female, color = female, linetype = female, size=female) # Added linetype aesthetic
    ) + 
    facet_wrap(
      . ~ condition, 
      ncol = 3, 
      labeller = labeller(condition = condition.labs)
    ) +
    geom_rect(
      aes(xmin = "60", xmax = "80", ymin = -Inf, ymax = Inf),
      alpha = 0.004,
      fill = "#344771",
      color= NA
    ) +
    theme_minimal() +
  geom_line(aes(size = female)) +  # Apply size mapping based on the 'female' variable
    geom_text(x = "55", y = 0.10, aes(label = label), data = f_labels, size = 9, color = "#050A30") +
    geom_text(x = "40", y = 0.17, aes(label = label), data = f_labels2, size = 9, color = "#8eb67d") +

    scale_fill_manual(values = c("#D3D3D3")) +        
    scale_color_manual(values = c("Male" = "#050A30", "Female" = "#8eb67d")) +  # Color Female lines with #8eb67d
    scale_linetype_manual(values = c("Male" = "longdash", "Female" = "solid")) +  # Line types for Male and Female
              scale_size_manual(values = c("Male" = 1, "Female" = 2)) +  # Thicker line for Female

    forma_theme
  
  return(graph)
}

fac_row_agg_count_out_gender <- function(
    data,
    vars,
    labels,
    forma_theme,
    size_count=10
){

  condition.labs <- labels
  names(condition.labs) <- vars
  condition_order <- measures[-length(measures)]

  
  data$condition <- factor(data$condition, levels = condition_order)

  levels(data$age_group5) <- c(levels(data$age_group5), '')
  f_labels <- data.frame(
    condition = condition_order,  
    female = c("Male",  "", "", "", "", "", "", "", ""),
    label = c("Male", "", "", "", "", "", "", "", "")
  )
  f_labels$condition = factor(f_labels$condition, levels = condition_order)

  f_labels2 <- data.frame(
    condition = condition_order,  
    female = c("Female",  "", "", "", "", "", "", "", ""),
    label = c("Female",  "", "", "", "", "", "", "", "")
  )
  f_labels2$condition = factor(f_labels2$condition, levels = condition_order)

  f_labels3 <- data.frame(
    condition = condition_order,  
    female = c("",  "", "", "", "", "", "", "", "Female"),
    label = c("",  "", "", "", "", "", "", "", "Female")
  )
  f_labels3$condition = factor(f_labels2$condition, levels = condition_order)

  
  f_labels4 <- data.frame(
    condition = condition_order,  
    female = c("",  "", "", "", "", "", "", "", "Male"),
    label = c("",  "", "", "", "", "", "", "", "Male")
  )
  f_labels4$condition = factor(f_labels2$condition, levels = condition_order)

  data$female <- factor(data$female, levels = c(1, 0), labels = c("Female", "Male"))
  
  graph <-data %>%  
    filter(condition!='healthinsurance_ever') %>% 
    ggplot(
    aes(x = age_group5, y = measurement, group = female, color = female, linetype = female, size = female)
      ) +
    facet_wrap(
      . ~condition, 
      ncol = 3, 
      labeller = labeller(condition=condition.labs)
      ) +
    geom_rect(
      aes(xmin = "60", xmax = "80", ymin = -Inf, ymax = Inf),
      alpha = 0.004,
      fill = "#344771",
      color= NA
        ) +
    theme_minimal() +
  geom_line(aes(size = female)) +  # Apply size mapping based on the 'female' variable
    geom_text(x = "65", y = 0.25, aes(label = label), data = f_labels, size = 9, color = "#050A30" ) +
    geom_text(x = "65", y = 0.55, aes(label = label), data = f_labels2, size = 9, color = "#8eb67d") +
    geom_text(x = "65", y = 0.35, aes(label = label), data = f_labels3, size = 9, color = "#8eb67d") +
    geom_text(x = "75", y = 0.22, aes(label = label), data = f_labels4, size = 9, color = "#050A30") +

        scale_fill_manual(values = c("#D3D3D3")) +        
    scale_color_manual(values = c("Male" = "#050A30", "Female" = "#8eb67d")) +  # Color Female lines with #8eb67d

      scale_linetype_manual(values = c("Male" = "longdash", "Female" = "solid")) +

          scale_size_manual(values = c("Male" = 1, "Female" = 2)) +  # Thicker line for Female
  coord_cartesian(clip = "off")  +# Ensure text isn't clipped

    forma_theme
  
  
  return (graph)
}

main_outco <- function(
  vars,
  labs,
  dat = dat_long,
  high = high_inco,
  sub = sub_sahar_inco,
  low = low_middle_inco,
  size_line = 1.1
) {
  graph = dat %>% 
    filter(variable %in% vars) %>% 
    ggplot(aes(reorder(country, order), value)) + 
    geom_bar(stat = "identity", fill = "white", color = "#1F271B", width = 0.85, size = 0.5) + 
    facet_grid(~factor(variable, levels = vars), scales = "free_x", labeller = as_labeller(labs)) +
    ylab("") + 
    xlab("") + 
    coord_flip() + 
    geom_hline(
      data = sub %>% filter(variable %in% vars), 
      aes(yintercept = value, color = "Sub-Saharan African Countries", linetype = "Sub-Saharan African Countries"),
      size = size_line+0.5, color = "#8eb67d"
    ) +
    geom_hline(
      data = low %>% filter(variable %in% vars), 
      aes(yintercept = value, linetype = "Low-middle Income Countries"),
      size = size_line, color = "#686868"
    ) +
    geom_hline(
      data = high %>% filter(variable %in% vars), 
      aes(yintercept = value, color = "High Income Countries", linetype = "High Income Countries"),
      size = size_line, color = "black"
    ) +
    guides(color = guide_legend(title = "Regional\nAverages", reverse = TRUE)) +
    scale_linetype_manual(name = "Regional\nAverages", values = c(3, 2, 1), 
                          guide = guide_legend(title = "Regional\nAverages", reverse = TRUE, 
                                               override.aes = list(color = c("#8eb67d", "#686868", "black")))) +
    theme_minimal() +
    theme_broad_outc() +
    
    # Assign labels to the countries in the plot
    geom_text(
      aes(label = ifelse(country %in% countries, country, ""),
          hjust = ifelse(country == "South Africa", 0.9, -0.05)), 
      color = "#344771", 
      size = 4.5
    ) 
    
  return(graph)
}

```

```{r include=FALSE}
outcomes_weighted_country = trans_input_count(
  subsaharan_weighted, measures
  ) 

outcomes_nonweighted_country = trans_input_count(
  subsaharan_nonweighted, measures
  ) 

outcomes_weighted_country_lim = trans_input_count(
  subsaharan_weighted, limitations
  )  


outcomes_nonweighted_country_lim = trans_input_count(
  subsaharan_nonweighted, limitations
  ) 


out_dis_weighted_gender = trans_input_count_gender(
  gender_weighted, measures
  )  

outcomes_weighted_gender = trans_input_count_gender(
  gender_weighted, limitations
  )  

```


```{r include=FALSE}

# Plot 2a
fig2a <- ggplot(totpop, aes(condition, measurement, fill = countryregion, label = countryregion)) +
  geom_area(type = "ridge", bw = 1) +
  geom_text(data = stacked_labels, aes(condition, measurement, label = labels), 
            hjust = 0, vjust = 0.5, color = stacked_labels$color, size = 8) +
  add_annotation(2100.2, cent(totpop, 1), "· 4.6B", "#818589", size_share) +
  add_annotation(2100.2, cent(totpop, 2), "· 0.8B", pal[3], size_share) +
  add_annotation(2100.2, cent(totpop, 3), "· 1.5B", pal[2], size_share) +
  add_annotation(2100.2, cent(totpop, 4), "· 3.4B", pal[1], size_share) +
  add_segment(2050, end_val(totpop, 2050)) +
  geom_point(aes(x = 2050, y = end_val(totpop, 2050)), color = "black") +
  add_annotation(2050, end_val(totpop, 2050) + 400000, "9.7B", "black", sz_tot) +
  add_segment(2020, end_val(totpop, 2020)) +
  geom_point(aes(x = 2020, y = end_val(totpop, 2020)), color = "black") +
  add_annotation(2020, end_val(totpop, 2020) + 400000, "7.8B", "black", sz_tot) +
  add_segment(1990, end_val(totpop, 1990)) +
  geom_point(aes(x = 1990, y = end_val(totpop, 1990)), color = "black") +
  add_annotation(1990, end_val(totpop, 1990) + 400000, "5.3B", "black", sz_tot) +
  add_segment(2100, end_val(totpop, 2100)) +
  geom_point(aes(x = 2100, y = end_val(totpop, 2100)), color = "black") +
  add_annotation(2100, end_val(totpop, 2100) + 400000, "10.3B", "black", sz_tot) +
  scale_fill_manual(values = pal) +
  coord_cartesian(clip = "off") +
  theme_minimal() +
  labs(title = '**A.** General Population (Total)', y = "", x = "") +
  theme(
    panel.grid = element_blank(),
    axis.text.y = element_blank(),
    plot.title = element_markdown(size = 20, color = "#344771", hjust = 0.5),
    axis.text.x = element_text(size = 20, margin = margin(5, 0, 0, 0)),
    plot.margin = margin(-1, 20, 0, 2),
    legend.position = "none"
  ) +
  scale_x_continuous(breaks = breaks_numer, labels = breaks_text)

# Plot 2b
fig2b <- ggplot(over60, aes(condition, measurement, fill = countryregion, label = countryregion)) +
  geom_area(type = "ridge", bw = 1) +
  add_annotation(2100.2, cent(over60, 1), "· 1.5B", "#818589", size_share) +
  add_annotation(2100.2, cent(over60, 2), "· 362M", pal[3], size_share) +
  add_annotation(2100.2, cent(over60, 3), "· 552M", pal[2], size_share) +
  add_annotation(2100.2, cent(over60, 4), "· 644M", pal[1], size_share) +
  add_segment(1990, end_val(over60, 1990)) +
  geom_point(aes(x = 1990, y = end_val(over60, 1990)), color = "black") +
  add_annotation(1990, end_val(over60, 1990) + 120000, "483M", "black", sz_tot) +
  add_segment(2020, end_val(over60, 2020)) +
  geom_point(aes(x = 2020, y = end_val(over60, 2020)), color = "black") +
  add_annotation(2020, end_val(over60, 2020) + 120000, "1,061M", "black", sz_tot) +
  add_segment(2050, end_val(over60, 2050)) +
  geom_point(aes(x = 2050, y = end_val(over60, 2050)), color = "black") +
  add_annotation(2050, end_val(over60, 2050) + 120000, "2,132M", "black", sz_tot) +
  add_segment(2100, end_val(over60, 2100)) +
  geom_point(aes(x = 2100, y = end_val(over60, 2100)), color = "black") +
  add_annotation(2100, end_val(over60, 2100) + 120000, "3,084M", "black", sz_tot) +
  scale_fill_manual(values = pal) +
  coord_cartesian(clip = "off") +
  theme_minimal() +
  labs(title = '**B.** Over 60 Population (Total)', y = "", x = "") +
  theme(
    panel.grid = element_blank(),
    axis.text.y = element_blank(),
    plot.title = element_markdown(size = 20, color = "#344771", hjust = 0.5),
    axis.text.x = element_text(size = 20, margin = margin(5, 0, 0, 0)),
    plot.margin = unit(c(0, 0.75, 0, 0), "inches"),
    legend.position = "none"
  ) +
  scale_x_continuous(breaks = breaks_numer, labels = breaks_text)

# Plot 2c

fig2c <- create_plot(
  totpop, 
  title = '**C.** General Population (Growth)', 
  y_limits = c(0, 500000, 1000000, 1500000, 2000000, 2500000, 3000000, 3500000), 
  y_labels = c("0", "-", "1B", "-", "2B", "-", "3B", "-")
) + geom_text_repel(
    aes(color = countryregion, label = name_lab),
    segment.angle = 10,
    size = 7.5,
    direction = "y",
    hjust = 0,
    vjust = 1.7,
    segment.size = .4,
    segment.alpha = .5,
    segment.linetype = "dotted",
    box.padding = .2,
    segment.curvature = -0.1
    ) 

# Plot 2d

fig2d <- create_plot(
  over60, 
  title = '**D.** Over 60 Population (Growth)', 
  y_limits = c(0, 200000, 400000, 600000, 800000), 
  y_labels = c("0", "-", "400M", "-", "800M")
) 



```


```{r pop_grow, echo=FALSE, fig.height=6, fig.width=5, dev = c("png"), dpi=100}
# Figure 1: Panel B: Over-60 population (m.)
newggslopegraph(
  dataframe = proj_pop,
  Times = measurement,
  Measurement = value,
  Grouping = country,
  Title = "",
  SubTitle = "",
  Caption = NULL,
  DataTextSize = 4,
  YTextSize = 4,
  XTextSize = 15,
  TitleTextSize = 10,
  SubTitleTextSize = 2,
  LineThickness = 1,
  LineColor = rep(c_green, nrow(proj_pop)),  # Repeating the color for each row
  WiderLabels = TRUE,
  ThemeChoice = "minimal"
  )
```

```{r ov60_pop, echo=FALSE, fig.height=7.5, fig.width=18, dev = c("png"), dpi=100}
# Figure 2: Projected Population Growth and Dependency Ratios
# Panels A & B
fig2a | fig2b  
```

```{r ov60_growth, echo=FALSE, fig.height=7.5, fig.width=18, dev = c("png"), dpi=100}
# Figure 2: Projected Population Growth and Dependency Ratios
# Panels C & D
fig2c | fig2d
```


```{r ov60_dep_rat, echo=FALSE, fig.height=7.5, fig.width=18, dev=c("png"), dpi=100}
# Figure 2: Projected Population Growth and Dependency Ratios
# Panels E & F
depratov60 <- create_dependency_ratio_plot(
  data = dep_rat_ov60,
  title = "**E.-** General Population (Dependency Ratio)",
  line_sizes = c(0.9, 0.9, 1.6),
  color_scheme = colors_scheme,
  breaks_numer = breaks_numer,
  breaks_text = breaks_text,
  include_country_labels = TRUE
)

oldageratov60 <- create_dependency_ratio_plot(
  data = old_age_rat_ov60,
  title = "**F.-** Over 60 Population (Dependency Ratio)",
  line_sizes = c(0.9, 0.9, 1.6),
  y_labels = c("0", "-", "0.5", "-", "1", "1.25", "1.50"),
  color_scheme = colors_scheme,
  breaks_numer = breaks_numer,
  breaks_text = breaks_text,
  include_country_labels = FALSE
)
wrap_elements(panel = depratov60  + oldageratov60 ) +
  labs(tag = "**Year**") +
  theme(
    plot.tag = element_markdown(size=20, color="#344771"),
    plot.tag.position = "bottom"
  )

```



```{r out_agg_ctr_wgt, echo=FALSE,  fig.height=25, fig.width=25, dev = c("png"), dpi=100}
# Figure 3: Employment, Health, & Living Arrangements over the Life Course: Aggregate
fac_row_agg_count_out(
  outcomes_weighted_country,
  measures,
  measures_labs_agg,
  theme_top_count())+ 
  labs(y = "Proportion", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+
  scale_y_continuous(breaks=c(0,0.5, 1), labels = c('0', '–', '1'))

```


```{r out_agg_gen_wgt,  echo=FALSE, fig.height=25, fig.width=25, dev = c("png"), dpi=100}
# Figure 4: Employment, Health, & Living Arrangements over the Life Course: by Gender
fac_row_agg_count_out_gender(
  out_dis_weighted_gender,
  measures,
  measures_labs_agg,
  theme_top_count()
  )+ 
  labs(y = "Proportion", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+
  scale_y_continuous(breaks=c(0,0.5, 1), labels = c('0', '–', '1'), limits = c(0, 1))
```


```{r dis_agg_ctr_wgt, echo=FALSE,  fig.height=12, fig.width=19, dev = c("png"), dpi=100}
# Figure 5: Functional Limitations over the Life Course
fac_row_agg_count_dis(
  outcomes_weighted_country_lim,
  limitations,
  limitations_labs,
  theme_top_count(
    size_text=23,
    size_title=28,
    size_legend=18,
    color="#344771"
  ))+ 
  labs(y = "Proportion", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+ 
  scale_y_continuous(breaks=c(0,0.5, 1), labels = c('0', '–', '1'), limits = c(0, 1))

```




```{r dis_agg_gen_wgt, echo=FALSE,  fig.height=12, fig.width=19, dev = c("png"), dpi=100}
# Figure 6: Functional Limitations over the Life Course By Gender
fac_row_agg_gen_dis(
  outcomes_weighted_gender,
  limitations,
  limitations_labs,
  theme_top_count(
    size_text=23,
    size_title=28,
    size_legend=18,
    color="#344771"
  ))+ 
  labs(y = "Proportion", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+ 
  scale_y_continuous(breaks=c(0,0.5, 1), labels = c('0', '–', '1'), limits = c(0, 1))  # Remove the legend

```

```{r hea_care, echo=FALSE, fig.height=7.5, fig.width=15, dev = c("png"), dpi=100}
# Figure 7: Social Protection across Selected Sub-Saharan African Countries
main_outco(
  vars=var_env,
  labs=labeller_environ
  )

```

```{r environ, echo=FALSE, fig.height=7.5, fig.width=18, dev = c("png"), dpi=100}
#Figure 8: Health Spending and Health Care Capacity across Selected Sub-Saharan African Countries
main_outco(
  vars=var_hea,
  labs=labeller_health
  )
```







```{r ov65_dep_rat, echo=FALSE, fig.height=7.5, fig.width=18, dev=c("png"), dpi=100}
# Online Appendix Figure A1: Dependency Ratios (over-65)

depratov65 = create_dependency_ratio_plot(
  data = dep_rat_ov65,
  title = "**A.-** General Population (Dependency Ratio)",
  line_sizes = c(1.4, 1.4, 1.4),
  color_scheme = colors_scheme,
  breaks_numer = breaks_numer,
  breaks_text = breaks_text,
  include_country_labels = TRUE
)

oldageratov65 <- create_dependency_ratio_plot(
  data = old_age_rat_ov65,
  title = "**B.-** Over 65 Population (Dependency Ratio)",
  line_sizes = c(0.9, 0.9, 1.6),
  y_labels = c("0", "-", "0.5", "-", "1", "1.25", "1.50"),
  color_scheme = colors_scheme,
  breaks_numer = breaks_numer,
  breaks_text = breaks_text,
  include_country_labels = FALSE
)

wrap_elements(panel = depratov65  + oldageratov65) +
  labs(tag = "**Year**") +
  theme(
    plot.tag = element_markdown(size=20, color="#344771"),
    plot.tag.position = "bottom"
  )
```


```{r outcomes_gender_weighted, echo=FALSE, fig.height=70, fig.width=45, dev = c("png"), dpi=100}
#Online Appendix Figure A3: Employment, Health, & Living Arrangements over the Life Course by Country and Gender WEIGHTED
graph_agg_data_main(weighted=TRUE)

```

```{r outcomes_aggregate_nonweighted, echo=FALSE,  fig.height=25, fig.width=25, dev = c("png"), dpi=100}
# Online Appendix Figure A5: Employment, Health, & Living Arrangements over the Life Course: Aggregate, no weights
fac_row_agg_count_out(
  outcomes_nonweighted_country,
  measures,
  measures_labs_agg,
  theme_top_count())+ 
  labs(y = "Proportion", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+
  scale_y_continuous(breaks=c(0,0.5, 1), labels = c('0', '–', '1'))

```

```{r outcomes_gender_nonweighted, echo=FALSE, fig.height=60, fig.width=45, dev = c("png"), dpi=100}
# Appendix: Figure 4 - Employment, Health, & Living Arrangements over the Life Course: Country-level, no weights
graph_agg_data_main(weighted=FALSE)

```

```{r disabilities_gender_weighted, echo=FALSE, fig.height=35, fig.width=45, dev = c("png"), dpi=100}
# Figure 7: Health and Health Care

b <- fac_row__("diff_seei", theme_top_a()) + 
  ylim(0, 1) + 
  labs(y = "          Seeing          ", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )   + theme(legend.position = "none") + scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))

c <- fac_row("diff_hear", theme_middle()) + 
  ylim(0, 1) + 
  labs(y = "  Hearing") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="top"
      )+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
d <- fac_row("diff_reme", theme_bottom()) +
  ylim(0, 1) + labs(y = "        Remembering", x = "")+ scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+  theme(legend.position = "none")+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
e <- fac_row("diff_walk_clim", theme_middle()) + ylim(0, 1) + labs(y = "   Walking or \n Climbing")+ scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="top"
      )+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
f <- fac_row("diff_self_care", theme_middle()) + ylim(0, 1) + labs(y = " Self Care", x = "Age")+ scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+  theme(legend.position = "none")+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))

i <- fac_row("diff_comm", theme_bottom()) + ylim(0, 1) + labs(y = "        Communicating", x = "\n\n\nAge")+ scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))

plot_grid(b, c, d, e, f, i, ncol=1, align='v', rel_heights = c(7.7, 5, 5.8, 5, 5, 9.8), labels =c("A.-", "B.-", "C.-","D.-", "E.-", "F.-"), label_size = 38,label_colour = "#14213D")

```

```{r disabilities_aggregate_nonweighted, echo=FALSE,  fig.height=12, fig.width=19, dev = c("png"), dpi=100}
# Online Appendix Figure A8: Functional Limitations over the Life Course: Aggregate, no weights
fac_row_agg_count_dis(
  outcomes_nonweighted_country_lim,
  limitations,
  limitations_labs,
  theme_top_count(
    size_text=23,
    size_title=28,
    size_legend=18,
    color="#344771"
  ))+ 
  labs(y = "Proportion", x = "Age") + 
  scale_x_discrete(
      breaks=bre_age,
      labels=lab_age,
      position="bottom"
      )+ 
  scale_y_continuous(breaks=c(0,0.5, 1), labels = c('0', '–', '1'), limits = c(0, 1))

```



    ```{r disabilities_gender_nonweighted, echo=FALSE, fig.height=35, fig.width=45, dev = c("png"), dpi=100}
    # Appendix: Figure 6 - Functional Limitations over the Life Course: Country-level, no weights
    b <- fac_row__("diff_seei", theme_top_a(), weighted=FALSE) + 
      ylim(0, 1) + 
      labs(y = "          Seeing          ", x = "Age") + 
      scale_x_discrete(
          breaks=bre_age,
          labels=lab_age,
          position="bottom"
          )   + theme(legend.position = "none") + scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))

    c <- fac_row("diff_hear", theme_middle(), weighted=FALSE) + 
      ylim(0, 1) + 
      labs(y = "  Hearing") + 
      scale_x_discrete(
          breaks=bre_age,
          labels=lab_age,
          position="top"
          )+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
    d <- fac_row("diff_reme", theme_bottom(), weighted=FALSE) +
      ylim(0, 1) + labs(y = "        Remembering", x = "")+ scale_x_discrete(
          breaks=bre_age,
          labels=lab_age,
          position="bottom"
          )+  theme(legend.position = "none")+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
    e <- fac_row("diff_walk_clim", theme_middle(), weighted=FALSE) + ylim(0, 1) + labs(y = "   Walking or \n Climbing")+ scale_x_discrete(
          breaks=bre_age,
          labels=lab_age,
          position="top"
          )+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))
    f <- fac_row("diff_self_care", theme_middle(), weighted=FALSE) + ylim(0, 1) + labs(y = " Self Care", x = "Age")+ scale_x_discrete(
          breaks=bre_age,
          labels=lab_age,
          position="bottom"
          )+  theme(legend.position = "none")+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))

    i <- fac_row("diff_comm", theme_bottom(), weighted=FALSE) + ylim(0, 1) + labs(y = "        Communicating", x = "\n\n\nAge")+ scale_x_discrete(
          breaks=bre_age,
          labels=lab_age,
          position="bottom"
          )+ scale_y_continuous(breaks=c(0,0.5, 1), limits = c(0, 1.2), labels = c('0', '-', '1'))

    plot_grid(b, c, d, e, f, i, ncol=1, align='v', rel_heights = c(7.7, 5, 5.8, 5, 5, 9.8), labels =c("A.-", "B.-", "C.-","D.-", "E.-", "F.-"), label_size = 38,label_colour = "#14213D")


    ```

