---
title: "Demography of Aging in South Saharan Africa"
output: 
  bookdown::pdf_document2:
    toc: false
    extra_dependencies: ["flafter"]
    number_sections: true
    df_print: kable
    highlight: tango
    keep_tex: true
    fig_caption: yes
fontsize: 11pt
geometry: margin=1in
header-includes:
  \usepackage{pdflscape}
  \usepackage{lscape}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.align = "center",
	fig.height = 4.5,
	fig.width = 5,
	message = FALSE,
	warning = FALSE,
  graphics.auto_pdf = FALSE
	)

```


\listoffigures
\newpage



```{r include=FALSE}
library(tidyr)
library(haven)
library(plyr)
library(dplyr)
library(ggplot2)
library(formattable)
library(ggh4x)
library(gridExtra)
library(ggtext)
library(CGPfunctions)


library(ggtree)
library(dplyr)
library(ggstance)
library(cowplot)
# devtools::install_github("YuLab-SMU/treeio")
# devtools::install_github("YuLab-SMU/ggtree")
library(tidytree)
library("ggsci")
library(stringr)


ssa = read_dta("../data/preprocessed/allcountries.dta")
ssa$gen <- ssa$female
ssa$female <- as.factor(ssa$female)

ssa$age_group5 <- as.factor(ssa$age_group5)

ssa = ssa %>% 
    mutate(
      female = case_when(
      female==0
       ~ 'Male',
      female ==1
      ~ 'Female',
      TRUE ~ NA), 
      country = case_when(
        country == 'eth'
         ~ 'ETHIOPIA',
        country == 'mlw'
         ~ 'MALAWI',  
        country == 'nga'
         ~ 'NIGERIA',  
        country == 'tza'
         ~ 'TANZANIA',  
        country == 'gha'
         ~ 'GHANA', 
        country == 'saf'
        ~ 'SOUTH AFRICA',
        country == 'uga'
         ~ 'UGANDA',
        TRUE ~ NA),
      work_hrs = case_when(
        work_hrs>=140 & work_hrs<=168 ~ 140,
        work_hrs>168 ~ NA,
        TRUE ~ work_hrs),
      region = case_when(
        country %in% c('ETHIOPIA', 'MALAWI', 'TANZANIA', 'UGANDA')
         ~ 'EASTERN AFRICA',  
        country  %in% c('GHANA', 'NIGERIA')
         ~ 'WESTERN AFRICA',
        TRUE ~ 'SOUTHERN AFRICA'
      ))
ssa$gender <- as.factor(ssa$female)
```


```{r echo=FALSE}

theme_top <- function(
    size_text=35,
    size_title=32,
    size_legend=32,
    color="#14213D"
){
  top = theme(
    axis.title.x = element_blank(),
    strip.background = element_rect(fill="white"),
    axis.text.x = element_blank(),
    axis.text.y = element_text(color = "#14213D", size = size_text),  
    legend.position="top", 
    legend.justification = "right",
    axis.ticks.x = element_blank(),
    legend.title=element_blank(),
    legend.text = element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend
      ),
    legend.key.size = unit(6,"line"), 

    text = element_text(size = size_text), 
    strip.text = element_text(color = color, size=size_title),
    axis.title.y = element_text(angle = 0),
    panel.spacing = unit(3, "lines")

    )

  return (top)
}


theme_middle <- function(
    size_text=35,
    size_title=35,
    color="#000C66"
){
  middle = theme(
    strip.background = element_blank(),
    strip.text.x = element_blank(), 
    legend.position="none",
    text = element_text(size = size_text),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_text(angle = 0),
    axis.text.y = element_text(color = "#14213D", size = size_text), 
    panel.spacing = unit(3, "lines")
    )

  return (middle)
}

theme_middle_wline <- function(
    size_text=20,
    size_title=35,
    color="#14213D"
){
  middle = theme(
    strip.background = element_blank(),
    strip.text.x = element_blank(), 
    legend.position="none",
    text = element_text(size = size_text),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.y = element_text(angle = 0),
    axis.line.x = element_line(size = 0.5, linetype="solid", colour=color),
    panel.spacing = unit(3, "lines")
    )

  return (middle)
}

theme_bottom <- function(
    size_text=35,
    size_title=15,
    size_legend=32,
    color="#000C66"
){
  bottom = theme(
    strip.background = element_blank(),
    strip.text.x = element_blank(), 
    legend.position="bottom", 
    legend.justification = "left",
    legend.title=element_blank(),
    legend.text = element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend
      ),
    legend.key.size = unit(6,"line"), 
    text = element_text(size = size_text),
    strip.text = element_text(color=color, size=size_title),
    axis.title.y = element_text(angle = 0),
    axis.text.y = element_text(color = "#14213D", size = size_text),  
    axis.text.x = element_text(color = "#14213D", size = size_text),
    panel.spacing = unit(3, "lines")

    )

  return (bottom)
}

get_count <- function(
    var
){
  annot0 = ssa %>% 
  filter(
    age==20 & gender=='Male'
    ) %>% 
  group_by(age_group5, country, gender, region) %>% 
  summarise(vari = mean(get(var), na.rm=TRUE))
  
  annot1 = ssa %>% 
    filter(
      age>=20 & !is.na(gender) 
      ) %>% group_by(country, gender) %>% 
    summarise(
      n = sum(!is.na(country)&!is.na(get(var)))
      ) %>% 
    group_by(country) %>% 
    summarise(n = paste0("N=", comma(sum(n), digits = 0)))
  
  count <- merge(annot0, annot1, by="country")
  
  return (count)
}


fac_row_popu <- function(
    forma_theme,
    colors=c("#8eb67d","#000C66"),
    breaks=c("20","25","30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80"),
    labels=c("20", "", "", "", "40", "", "",  "", "60", "", "", "", "80+"),
    size_count=12

){
  
  dat = get_count("gender")

  graph <- ssa %>%
    filter(age>=20  & !is.na(gender))%>%  ggplot(
      aes(x = age_group5, fill=gender)
      ) + 
    theme_minimal() +
    geom_bar(binwidth = 0.5, color  = "white", position = "dodge") +
    facet_nested(~region+country, scales='free_y', space="free_y") +
    scale_fill_manual("legend", values = c("Female" = "#8eb67d", "Male" = "#000C66"))+
    geom_text(
      data = dat, 
      label = dat$n,
      aes(label = paste0("N=", n), y = Inf, x  = -Inf),
      vjust = 1,
      colour="#14213D",
      hjust = -0.2,
      size = size_count
      ) + 
    forma_theme
  
  return (graph)
}


fac_row <- function(
    var,
    forma_theme,
    colors=c("#8eb67d","#000C66"),
    size_count=12
){
  
  dat = get_count(var)
  
  graph <- ssa %>% 
    filter(
      age>=20 & !is.na(gender) 
      ) %>% 
    group_by(age_group5, country, gender, region) %>% 
    summarise(vari = mean(get(var), na.rm=TRUE)) %>% 
    ggplot(
      aes(x = age_group5, y = vari, colour = gender, group=gender)
      ) + 
    theme_minimal() +
    geom_line(size = 3, aes(linetype=gender)) +
    facet_nested(~region+country, scales='free_y', space="free_y") +
    scale_color_manual(values = colors) +
    scale_linetype_manual(values=c("solid", "longdash"))  +
    geom_text(
      data = dat, 
      label=dat$n,
      aes(label = paste0("N=", n), y = Inf, x  = -Inf),
      vjust = 1,
      colour="#14213D",
      hjust = -0.2,
      size = size_count
      ) +
      geom_rect(aes(xmin = "60", xmax = Inf, ymin = -Inf, ymax = Inf),
            alpha = 0.005,
            fill = "#8eb67d") +
  # Shade area above y_lim
    forma_theme

  
  return (graph)
}

```

\begin{landscape}

```{r employmenthours, fig.cap="Employment. Age Group and Gender.", echo=FALSE, fig.height=35, fig.width=40, dev = c("png", "tiff"), dpi=400}
breaks=c("20","25","30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80")

labels=c("20", "", "", "", "40", "", "",  "", "60", "", "", "", "80+")
a <- fac_row_popu( theme_top()) + labs(y = "Observations \n(Count)") + scale_x_discrete(
      breaks=breaks,
      labels=labels,
      position="top"
      )
b <- fac_row("urban", theme_bottom()) + ylim(0, 1) + labs(y = "Urban Status\n(Proportion)", x = "Age")+ scale_x_discrete(
      breaks=breaks,
      labels=labels,
      position="bottom"
      )+  theme(legend.position = "none")
c <- fac_row("work_any", theme_middle()) + ylim(0, 1) + labs(y = "Employment\n(Proportion)")+ scale_x_discrete(
      breaks=breaks,
      labels=labels,
      position="top"
      )
d <- fac_row("work_hrs", theme_bottom()) + labs(y = "Employment\n(Hours)", x = "Age")+ scale_x_discrete(
      breaks=breaks,
      labels=labels,
      position="bottom"
      )+  theme(legend.position = "none")
e <- fac_row("notmarried", theme_middle()) + ylim(0, 1) + labs(y = "Living Arrangements\nUnmarried\n(Proportion)")+ scale_x_discrete(
      breaks=breaks,
      labels=labels,
      position="top"
      )
f <- fac_row("lives_alone", theme_bottom()) + ylim(0, 1) + labs(y = "Living Arrangements\nLives alone\n(Proportion)", x = "Age")+ scale_x_discrete(
      breaks=breaks,
      labels=labels,
      position="bottom"
      )+  theme(legend.position = "none")
g <- fac_row("ill_inj", theme_middle()) + ylim(0, 1) + labs(y = "Health\nIllness/Injury\n(Proportion)")+ scale_x_discrete(
      breaks=breaks,
      labels=labels,
      position="top"
      )
h <- fac_row("ill_inj_stopactivity", theme_middle()) + ylim(0, 1) + labs(y = "Health\nStopped\nActivities\n(Proportion)")+ scale_x_discrete(
      breaks=breaks,
      labels=labels,
      position="top"
      )
i <- fac_row("depressed", theme_bottom()) + ylim(0, 1) + labs(y = "Psychological Health\nDepression", x = "Age")+ scale_x_discrete(
      breaks=breaks,
      labels=labels,
      position="bottom"
      )
plot_grid(plotlist=list(a, b, c, d, e, f, g, h, i), ncol=1, align='v', rel_heights = c(12, 7, 5, 6.5, 5, 6.5, 5, 5, 10))

```


\end{landscape}



```{r echo=FALSE}
projections = read_dta(
  '../../../Demography of Aging in SSA/data/population_projections.dta'
  )

proj_pop = projections %>% 
  rename(
  '1990'= pop_60plus_1990, 
  '2020'= pop_60plus_2020, 
  '2050'= pop_60plus_2050
  ) %>% select(
  countryregion, '1990', '2020', '2050'
)

proj_pop = rapply(
  object = proj_pop,
  f = round,
  classes = "numeric",
  how = "replace",
  digits = 0
  ) 
proj_pop = gather(
  proj_pop,
  measurement,
  value,
  '1990':'2050',
  factor_key=TRUE
  )
proj_pop = proj_pop %>% 
  filter(
    countryregion %in% 
      c('South Africa', "Ghana", "Uganda", "Tanzania", "Nigeria", "Ethiopia", "Malawi")
    )

proj_pop = proj_pop %>% mutate(
  value=value/1000
) %>%  mutate(across(c('value'), round, 1))
```



```{r popplus60, echo=FALSE, fig.height=6, fig.width=5, dev = c("png", "tiff", "pdf"), dpi=300}
newggslopegraph(
  dataframe = proj_pop,
  Times = measurement,
  Measurement = value,
  Grouping = countryregion,
  Title = "Over 60 Population in Millions",
  SubTitle = "",
  Caption = NULL,
  DataTextSize = 4,
  YTextSize = 4,
  XTextSize = 15,
  TitleTextSize = 10,
  SubTitleTextSize = 2,
  LineThickness = 1,
  LineColor = c(rep("#8eb67d",7)),
  WiderLabels = TRUE,
  ThemeChoice = "minimal"
  )
```


```{r}
dat = read_dta('../../../Demography of Aging in SSA/data/policyenvironment.dta')

dat = dat %>% 
  filter((country!="Low & middle income") & (country!="Middle income") & (country!="Low income") & (country!="Sub-Saharan Africa"))

dat = dat %>% select('country', 'physicians', 'hospbeds', 'govtexpgdp', 'oopexp', 'pension_coverage_oldage')

dat <- dat[order(dat$govtexpgdp,decreasing=TRUE),]

dat$cou = c(0,1,0,1,0,1,1,1,1,1)

dat_1 = dat %>% filter(cou!=0)

dat_1$govtexpgdp=dat_1$govtexpgdp

dat_1$oopexp=-(dat_1$oopexp-100)

dat_1$pension_coverage_oldage=dat_1$pension_coverage_oldage
```

```{r}
dat_1 = dat_1 %>% select(govtexpgdp, oopexp, pension_coverage_oldage, hospbeds, physicians, country, cou)
```

```{r}
dat_long = gather(dat_1, variable, value, govtexpgdp:physicians, factor_key=TRUE)

dat_long = dat_long %>%                          # Applying row_number function
  mutate(order = row_number())
```

```{r}
theme_spac <- function(
    size_text=10,
    size_title=10,
    size_legend=7,
    color="#14213D"
){
  top = theme(
    axis.title.x = element_blank(),
    strip.background = element_rect(fill="white"),
    #axis.text.x = element_blank(),
    axis.text.y = element_text(color = "#14213D", size = size_text),  
    #legend.position="top", 
    legend.justification = "right",
    axis.ticks.x = element_blank(),
    #legend.title=element_blank(),
    legend.text = element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend
      ),
    legend.key.size = unit(2,"line"), 

    text = element_text(size = size_text), 
    strip.text = element_text(color = color, size=size_title),
    axis.title.y = element_text(angle = 0),
    panel.spacing = unit(1, "lines")

    )
}

dat_0 = dat %>% filter(cou!=1)

dat_0 = dat_0 %>% select(govtexpgdp, oopexp, pension_coverage_oldage, hospbeds, physicians, country, cou)

dat_long_0 = gather(dat_0, variable, value, govtexpgdp:physicians, factor_key=TRUE)

dat_long_0 = dat_long_0 %>%                          # Applying row_number function
  mutate(order = row_number())
```




```{r}

high_inco = data.frame(
  variable = c("govtexpgdp", "oopexp", "pension_coverage_oldage", "hospbeds", "physicians"), 
  value = c(7.722377, 13.63032, NA, 5.280971, 3.1600544),
  type= c("high_inco", "high_inco", "high_inco", "high_inco", "high_inco")
  )

low_middle_inco = data.frame(
  variable = c("govtexpgdp", "oopexp", "pension_coverage_oldage", "hospbeds", "physicians"), 
  value = c(2.935153, 36.39225, NA, 2.520665, 1.5626701)
  )

sub_sahar_inco = data.frame(
  variable = c("govtexpgdp", "oopexp", "pension_coverage_oldage", "hospbeds", "physicians"), 
  value = c(2.015232, 29.98320, NA, 1.211261, 0.2332769)
  )
```


```{r coor, echo=FALSE, fig.height=2.5, fig.width=15, dev = c("png", "tiff", "pdf"), dpi=300}

new_labeller <- c(
  `govtexpgdp`="Gov. Health Expenditure\n(Percentage of GDP)",
  'oopexp'="Non-out of Pocket\nHealth Expenditure\n(Percentage)",
  'pension_coverage_oldage'="Pension Coverage\n(Percentage)",
  'hospbeds'="N째 of Hospital Beds\n(Per 1,000)",
  'physicians'="N째 of Physicians\n(Per 1,000)"
)
ggplot(dat_long, aes(reorder(country, order), value)) + 
  #eom_point() + 
  geom_bar(stat = "identity", fill = "white", color="#1F271B", size=0.4) + 
  facet_grid(~variable, scales = "free_x", labeller= as_labeller(new_labeller)) + 
  ylab("") +
  xlab("") + 
  coord_flip() + 
  geom_hline(data = high_inco, aes(yintercept = value, color="High Income Countries"))+#, linetype="twodash", size=0.5) +
  geom_hline(data = low_middle_inco, aes(yintercept = value, color="Low-middle Income Countries"))+#, linetype="dotdash", size=0.5)+
  geom_hline(data = sub_sahar_inco, aes(yintercept = value, color="Sub-saharan African Countries"))+#, linetype="longdash", size=0.5) +
  guides(color=guide_legend(title="Regions (Avg)"))+
  scale_color_manual("Regions (Avg)", values = c("#000C66", "#800000", "#E1AD01" )) +
  #scale_linetype_manual("Regions (Avg)", values=c("twodash", "dotdash", "longdash")) +
  theme_minimal() +
  theme_spac() 



```


```{r coor_2, echo=FALSE, fig.height=3.4, fig.width=15, dev = c("png", "tiff", "pdf"), dpi=300}

new_labeller <- c(
  `govtexpgdp`="Gov. Health Expenditure\n(Percentage of GDP)",
  'oopexp'="Non-out of Pocket\nHealth Expenditure\n(Percentage)",
  'pension_coverage_oldage'="Pension Coverage\n(Percentage)",
  'hospbeds'="N째 of Hospital Beds\n(Per 1,000)",
  'physicians'="N째 of Physicians\n(Per 1,000)"
)
n <-ggplot(dat_long_0, aes(reorder(country, order), value)) + 
  #eom_point() + 
  geom_bar(stat = "identity", fill = "white", color="#1F271B", size=0.4) + 
  facet_grid(~variable, scales = "free_x", labeller= as_labeller(new_labeller)) + 
  ylab("") +
  xlab("") + 
  coord_flip() + 
  theme_minimal() +
  theme_spac() 


theme_spac_0 <- function(
    size_text=10,
    size_title=10,
    size_legend=7,
    color="#14213D"
){
  top = theme(
    axis.title.x = element_blank(),
    strip.background = element_blank(),
    strip.text.x = element_blank(),
    #axis.text.x = element_blank(),
    axis.text.y = element_text(color = "#14213D", size = size_text),  
    legend.position="None", 
    legend.justification = "right",
    axis.ticks.x = element_blank(),
    legend.title=element_blank(),
    legend.text = element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend
      ),
    legend.key.size = unit(2,"line"), 

    text = element_text(size = size_text), 
    strip.text = element_text(color = color, size=size_title),
    axis.title.y = element_text(angle = 0),
    panel.spacing = unit(1, "lines")

    )
}

theme_spac <- function(
    size_text=10,
    size_title=10,
    size_legend=7,
    color="#14213D"
){
  top = theme(
    axis.title.x = element_blank(),
    strip.background = element_rect(fill="white"),
    #axis.text.x = element_blank(),
    axis.text.y = element_text(color = "#14213D", size = size_text),  
    #legend.position="top", 
    legend.justification = "right",
    axis.ticks.x = element_blank(),
    #legend.title=element_blank(),
    legend.text = element_text(
      margin = margin(t = size_legend, b = size_legend, unit = "pt"),
      size=size_legend
      ),
    legend.key.size = unit(2,"line"), 

    text = element_text(size = size_text), 
    strip.text = element_text(color = color, size=size_title),
    axis.title.y = element_text(angle = 0),
    panel.spacing = unit(1, "lines")

    )
}




m<-ggplot(dat_long, aes(reorder(country, order), value)) + 
  #eom_point() + 
  geom_bar(stat = "identity", fill = "white", color="#1F271B", size=0.4) + 
  facet_grid(~variable, scales = "free_x", labeller= as_labeller(new_labeller)) + 
  ylab("") +
  xlab("") + 
  coord_flip() + 
  geom_hline(data = high_inco, aes(yintercept = value, color="High Income Countries"), linetype="twodash", size=0.5, alpha=.0) +
  geom_hline(data = low_middle_inco, aes(yintercept = value, color="Low-middle Income Countries"), linetype="dotdash", size=0.5, alpha=0)+
  geom_hline(data = sub_sahar_inco, aes(yintercept = value, color="Sub-saharan African Countries"), linetype="longdash", size=0.5, alpha=0) +
  guides(color=guide_legend(title="Regions (Avg)"))+
  scale_color_manual("Regions (Avg)", values = c("white", "white", "white" )) +
  scale_linetype_manual("Regions (Avg)", values=c("twodash", "dotdash", "longdash")) +
  theme_minimal() +
  theme_spac_0() 



plot_grid(plotlist=list(n, m), ncol=1, align='v', rel_heights = c(14, 18))

```


